- rebar.lock
- src/miner_sup.erl
- src/poc/miner_poc_statem.erl
- test/miner_poc_SUITE.erl
While working on finishing up #203, which this PR supersedes and is based upon, I decided that there were flaws in the way that delay was being done.  This change rebases the original PR on newer code, then changes the delay mechanism to an interval-proportional probabalistic jitter before the request, rather than before the submission of the receipt.  This allows us to do a few things:
- simplify the state, as we no longer need to keep the delay counter or save anything between transitions
- improve jitter performance even in the case of state loss
- deliver receipts more promptly
This change *should* do a more effective job of spreading challenges out throughout the challenge interval, since it applies the jitter at the chain-anchored start of the process, rather than the state …
> save progress, change delay

- config/dev.config
- src/handlers/miner_hbbft_handler.erl
add the ability to dump failing txns on a live node to disk, disabled by default.
> add transaction dumping for live debugging

- src/miner_hbbft_sidecar.erl
wrap the call in a spawn for a quick fix.
> fix another sync call in the sidecar to break a temporary deadlock

- test/miner_ct_utils.erl
miner_ct_utils was missing an export for new_random_key function
> add missing export for new_random_key function

- src/poc/miner_onion_server.erl
- test/miner_onion_SUITE.erl
Just send the packet on, don't block on the receipt.
> Fix onion server test, Remove unnecessary send receipt check

- config/sys.config
```ubuntu@ip-172-31-63-147:~$ ./connect.sh tall-blonde-condor
Warning: Permanently added '[localhost]:38397' (ECDSA) to the list of known hosts.
helium@localhost's password: 
$ sudo su -
3404		138655
Erlang/OTP 22 [erts-10.5] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1]Eshell V10.5  (abort with ^G)
(miner@127.0.0.1)1> {ok, Block} = blockchain:get_block(138655, blockchain_worker:blockchain()).
{ok,{blockchain_block_v1_pb,<<65,51,77,64,29,224,90,167,
196,21,42,41,199,32,25,14,
67,246,252,62,164,230,82,
167,163,...>>,
...
(miner@127.0.0.1)2> rp(blockchain_block:hash_block(Block)).
<<31,254,105,232,128,247,123,59,86,163,223,180,66,181,158,
160,206,153,103,176,201,109,141,196,54,44,231,231,218,
71,120,42>>
ok
(miner@127.0.0.1)3> rp(blockchain_block:height(Block)).
138655
ok
```
> Bump assumed valid block to 138655

- test/miner_ct_utils.erl
- test/miner_libp2p_SUITE.erl
- test/miner_poc_SUITE.erl
Instead of leaving behind dozens of gigabytes of logs and
blockchain/ledger databases for each test run, if the test suceeds.
delete all the logs and databases at the end of the run.
Additionally use init/end per testcase functions for the poc suite so
that it better matches the other suites and ensures node shutdown after
the test finishes.
> Clean up test data and logs on common test success

- src/cli/miner_cli_info.erl
Adds support for 'info summary' which returns key data points for a miner.
NOTE: the ticket defined some data points which are not included in this PR:
- Date and block # when gateway was added to chain
We do not have any ready means to determine this data currently but it may be added as a separate ticket.
./miner/bin/miner info summary usage
Usage: info summary 
Get a collection of key data points for this miner.
Also returns the last 5 error log entries across 3 categories: Transactions, POCs and Other errors.
By default the latest 500 log entries are scanned and the most recent 5 hits for each category returned
Options
-e, --error_count <count>     Set the count of log entries to return per category)
-s, --scan_range <range>     Set the maximum number of log entries to scan …
> add support for new cli command: info summary

- src/miner.erl
- src/miner_hbbft_sidecar.erl
- src/poc/miner_poc_statem.erl
a lot of servers tend to leak binaries, spread the hibernation magic widely
> hibernate servers that tend to leak bins

- src/cli/miner_cli_info.erl
Correct expected return value when a gateway is found.
Treat any non {ok, GW} response as not found rather than restricting it to solely {error, Reason}
> properly handle find_gateway_info response

- src/poc/miner_poc_statem.erl
This refactor addresses the following:
1.  Eliminate potential for the statem process to become 'stuck', that is to get into a state in which it cannot exit as no potential for expected events to arrive.  To address this I have:
- Eliminated the use of self targeted msgs
- Ensured all supported states consume and react to externally generated msgs and thus will always have something to react to even after a restart without a need to artificially generate events via self msg or other means
- Added a fail safe for the number of times the statem can be unsuccessfully restarted, if it is fails to complete a POC N times it will give up on the current POC and transition to requesting state
2.  Remove unnecessary states ( 'targetting', 'challenging' and 'submitting' )
NOTE: Challenging and …
> refactor of statem

- src/poc/miner_poc_statem.erl
in certain circumstances, we can infinitely loop on bad targeting paths because the retry got misplaced during the refactor.
> fix infinite loop in poc statem targeting error

- src/poc/miner_poc_statem.erl
We hit a crash bug on a hotspot which resulted from an empty poc statem file being present on the file system.
This resulted in the binary_to_term on the empty binary crashing with a bararg error
This PR appropriately handles the empty file and goes further to accommodates a file which may have a badly encoded term ( such as if the file was manually edited or the system crashed out mid writing )
> handle empty poc statem files and also those with a badly encoded term

- src/handlers/miner_hbbft_handler.erl
- src/miner_consensus_mgr.erl
this seems to have gotten lost in my latest refactor of this stuff.  With this, we'll bad_sup instead of properly signaling that we're not in the group anymore.  This should remove some confusion as to when we're getting a bad_sup for other reasons, and when we've just exited the group.
> notify the miner that we're out

- src/cli/miner_cli_info.erl
Fixes crash when trying to output the bin version of owner address, we now convert this to the p2p version
Manually patched my own hotspot and confirmed it resolves the issue and no additional issues encountered
> use p2p version of owner address

- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
- test/miner_dkg_SUITE.erl
- test/miner_libp2p_SUITE.erl
- test/miner_onion_SUITE.erl
- test/miner_payment_txn_SUITE.erl
- test/miner_poc_SUITE.erl
- test/miner_reward_SUITE.erl
- test/miner_router_SUITE.erl
- test/miner_txn_bundle_SUITE.erl
Changes include:
1. Force common test to use priv_dir as the base scratch location. All logs, assets, artefacts such as DBs etc will be written relative to here.  Base dir data is included in the Config prop.   Each test has its own private scratch per run using a combination of the test module plus test case as the naming convention.
2.  Tidied up CTs to use ?config macro when accessing data from Config prop
2.  Whilst none of the existing eunit tests use the tmp_dir, i have modified this to be consistent with both libp2p and blockchain-core.  Tmp dir location for unit tests is now relative to '_build' dir.   Function also included to cleanup tmp dir assets
> change tmp dir to be relative from _build dir

- config/sys.config
```
(miner@127.0.0.1)2> rp(blockchain_block:hash_block(Block)).
<<104,251,74,43,120,160,101,163,179,105,182,101,206,26,73,
93,114,15,239,168,203,1,77,53,201,67,53,35,96,157,144,
243>>
ok
(miner@127.0.0.1)3> rp(blockchain_block:height(Block)).
196777
ok
```
> Bump assumed valid block to 196777

- rebar.config
- scripts/extensions/print_keys
- src/miner_ebus.erl
- src/miner_keys.erl
- src/miner_sup.erl
This adds a miner/bin/print_keys shell script that prints out a list of terms for onboarding/pub keys. 
To get this to work the miner_sup startup for key retrieval was moved into a new miner_keys module
> Add print_keys script

- src/miner_lora.erl
- test/miner_ct_utils.erl
- test/miner_poc_SUITE.erl
* Use reuseaddr so we have a better chance of grabbing the port after a
crash, or during tests
* Assume any non onion packet is a lorawan packet, we've seen some false
positives
> Tweak the behaviour of miner_lora a bit

- config/sys.config
```
Eshell V10.5  (abort with ^G)
(miner@127.0.0.1)1> {ok, Block} = blockchain:get_block(249675, blockchain_worker:blockchain()).
{ok,{blockchain_block_v1_pb,
<<32,211,76,111,62,245,167,155,205,142,128,125,134,119,84,
1,237,146,109,43,216,39,8,16,122,...>>,
249675,1584372738,249697,
...
(miner@127.0.0.1)2> rp(blockchain_block:hash_block(Block)).
<<244,213,32,200,79,169,196,15,172,236,87,100,234,37,75,
250,184,39,108,110,175,130,200,54,117,56,116,127,222,94,
120,103>>
ok
(miner@127.0.0.1)3> rp(blockchain_block:height(Block)).
249675
ok
```
> Bump assumed valid block to 249675

- src/miner_sup.erl
- src/poc/miner_onion_server.erl
- test/miner_onion_SUITE.erl
the POC suite has a tendency to fail randomly.  I traced this back to the onion server crashing out a number of times in quick succession and breaching the miner_sup restart intensity leading to the entire miner tree restarting.
Each poc suite test initialises with the the following:
{_, Locations} = lists:unzip(initialize_chain(Miners, TestCase, Config, VarMap)),
GenesisBlock = get_genesis_block(Miners, Config),
miner_fake_radio_backplane:start_link(maps:get(?poc_version, VarMap), 45000, lists:zip(lists:seq(46001, 46000 + MinerCount), Locations)),
timer:sleep(5000),
true = load_genesis_block(GenesisBlock, Miners, Config),
As part of `initialize_chain` there is a call to the consensus mgr to do the initial_dkg.   For those nodes part of the CG group this takes sufficient time to complete …
> Fix potential instability in POC test suite 

- src/miner.erl
The existing catchup function isn't really aggressive enough for the current network quality.   This change does two things:
1) We square the difference (and cap it to 15s), so that we push more aggressively to 0 when we drift.
2) we invert the logic for slowdown, so that we're tight around 0, rather than drifting up to 1s fast before we start to correct.
> increase catchup, and also slowdown

- config/sys.config
```
{ok, Block} = blockchain:get_block(263260, blockchain_worker:blockchain()).
...
(miner@127.0.0.1)2> rp(blockchain_block:hash_block(Block)).
<<1,70,42,104,128,154,186,190,212,63,116,233,134,57,145,
177,109,89,25,120,157,32,84,156,247,189,255,113,204,143,
78,80>>
ok
(miner@127.0.0.1)3> blockchain_block:height(Block).
263260
```
> Bump assumed valid block to 263260

- src/handlers/miner_hbbft_handler.erl
- src/miner.erl
- src/miner_hbbft_sidecar.erl
Prior to this change, we had 2 calls to a sidecar transaction filter
operation, one of them was done as soon as the block's contents were
agreed on and one was done at the start of a new round, if the prior
filtering had not been done.
The prefilter had a problem that it didn't tell the sidecar what
transactions were pending. This led to the sidecar rejecting all
transactions that depended on the transactions about to appear in the
next block.
This change adds an explicit prefilter that absorbs the valid
transactions from the pending block and then re-evaluates all the
buffered transactions against that. This means that transactions that
depend on the tranactions in the pending block will no longer be
filtered out.
Additionally, this change seperates pending transactions in the next
block …
> Use an explicit prefilter when a hbbft transaction set has been agreed

- src/handlers/miner_hbbft_handler.erl
I'm not certain that this is a major problem, but it's certainly incorrect behavior.
> using the wrong threshold in early gossip exit

- rebar.lock
- test/miner_ct_utils.erl
- test/miner_payment_txn_SUITE.erl
- test/miner_txn_mgr_SUITE.erl
Update test to account for txn mgr's txn_list returning a map of txns ( key: txn, value: TxnData )
tweak some test timers for better stability
Associated blockchain core pr: 
https://github.com/helium/blockchain-core/pull/431
> bump to blockchain core version with txn mgr cache as records

- .buildkite/pipeline.yml
- test/miner_blockchain_SUITE.erl
- test/miner_ct_macros.hrl
- test/miner_ct_utils.erl
This fixes the miner's blockchain_SUITE election test. Two primary problems are addressed:
1. The test includes a call to blockchain_gossip_handler:add_block. This arity here was incorrect since helium/blockchain-core@4051502#diff-70ab3c21b9b17903889bfc6a4d66fac4
2. Instability was introduced to the test with an incorrect use of miner_ct_util:wait_for_gte since the miner tests were refactored by me back in November. I compared the current against the test prior to this work and made a number of corrections.
> Fix blockchain_SUITE's election test

- config/sys.config
The `/var/log` directory is mounted as tmpfs so it does not wear down the microSD.
> Log to /var/log/miner not /var/data/log/miner

- .buildkite/scripts/Dockerfile-amd64
- .buildkite/scripts/Dockerfile-arm32
- .buildkite/scripts/Dockerfile-arm64
- README.md
The main changes here are that the miner is run in foreground, allowing `docker run` to return when `-d` option is used.
In addition, `/opt/miner/bin` is added to PATH so that interrogating miner is simpler, ie:
`docker exec happy_lamport miner info height`
rather than 
`docker exec happy_lamport /opt/miner/bin/miner info height`
Also, a teensy bit of documentation is added about how to build a test Docker image locally.
Fuller documentation on the docker will be available on developer.helium.com
> Docker tweaks

- config/sys.config
- src/miner_collect.erl
- src/miner_lora.erl
- src/miner_query.erl
- src/miner_util.erl
- src/poc/miner_onion_server.erl
- src/poc/miner_poc_statem.erl
- test/miner_fake_radio_backplane.erl
- test/miner_poc_SUITE.erl
This is a WIP version to get some feedback on the approach here.
The idea is that we skim GPS info off of our status packet and store it in the `miner_lora` server.  Then we check if it's close enough to our asserted position to see if we're allowed to make any requests.
Main questions here: 
1. Is 75 meters too lenient? Too strict?
2. Some other GPS using PRs we do some additional position adjustment, do we need to do those here?
> Don't challenge without GPS lock close to assert

- src/miner_consensus_mgr.erl
this is causing a lot of noise and perhaps occasional restarts on the miners while they're loading snapshots.
> don't crash when someone checks consensus without a proper ledger

- src/miner_lora.erl
75m has been deemed too strict.
> adjust wander dist to 200m

- src/miner_consensus_mgr.erl
we saw some timeouts when the system was very busy, there's no point in this being a call, even if it should generally complete quickly.
> no reason for this to be a call

- config/sys.config
I think that this should be safe, we cranked these down too low before discovering the batch leak issue.
> update rocks tunings to use more memory

- src/miner_consensus_mgr.erl
when we restore an older election, we need to use the ledger at that height, otherwise we might get the wrong group and think erroneously that we're not in the election group.
> on restore, we can't use the current ledger

- config/dev.config
- config/test.config
- src/miner_lora.erl
- src/miner_sup.erl
- test/miner_ct_utils.erl
- test/miner_onion_SUITE.erl
This enables the operating region to be supplied via the sys config or directly via an os level env var.  The sys config value will take precedence.  If the region is not supplied via either of these two options, miner will attempt to derive the region from the asserted location ( no changes there ).
the expected application env var in sys config is 'region_override'
the expected OS env var is 'REGION_OVERRIDE'
Valid values for both are:
US915 | EU868 | EU433 | CN470 |  CN779 | AU915 | AS923 | KR920 | IN865
The OS env var is not templated in the sys config file as doing so necessities the env var having to exist/be set otherwise the sys config file will not derive a value for the key and thus fail to boot.  I didnt want to make setting the env var a pre-requisite.   I can make it a …
> allow region to be supplied via os env var or via sys config

- config/sys.config
```
Height 407521
Hash <<14,196,182,77,149,18,208,15,23,98,199,126,160,64,80,206,122,207,202,182,
239,121,147,70,61,242,192,55,252,72,192,189>>
Have true
Height 406801
Hash <<177,4,62,0,171,246,17,99,170,201,33,8,225,112,54,130,35,246,177,185,75,
96,9,10,118,223,173,173,140,251,54,187>>
Have true
Height 406081
Hash <<160,4,204,95,92,218,127,233,166,240,97,77,61,237,224,113,46,230,113,162,
31,156,178,99,120,45,17,107,178,98,166,97>>
Have true
Height 405361
Hash <<110,142,201,15,171,138,49,171,116,90,159,253,41,9,214,7,204,77,182,220,
57,169,236,218,172,186,68,127,244,28,70,149>>
Have true
Height 404641
Hash <<65,147,230,145,148,102,65,101,157,210,191,150,67,183,125,102,133,234,
240,239,70,28,191,55,29,53,43,87,204,241,67,121>>
Have true
```
> Bump blessed snapshot to 407521

- config/sys.config
```
Height 417601
Hash <<115,116,117,15,101,91,238,141,114,6,155,94,229,3,60,14,94,22,34,100,42,
190,162,59,62,34,194,129,170,93,122,228>>
Have true
```
> Bump blessed snapshot to 417601

- src/miner_consensus_mgr.erl
we're still seeing some failures of consensus members to start with the current 30s timeout, so increase it.
> Increase the timeout for dkg completion/hbbft start

- rebar.lock
This should allow users to re-assert their Hotspot's location from the mobile app.
> Bump core for empty Payer58

- src/miner_lora.erl
We are dropping a non-negligible number of downlink lora packets due to the way we track a gateway's UDP port. The Semtech packet forwarder opens two sockets, one for pushing messages to the server, and one for pulling. We currently update the source port on both PUSH_DATA and PULL_DATA messages. This has the adverse effect of miner sending downlink packets to the wrong port after receiving PUSH_DATA messages. Instead, we should only track the source port for PULL_DATA while still sending PUSH_ACKs to their correct port.
> Prevent dropped downlink packets

- config/sys.config
```
Height 435601
Hash <<154,106,138,139,216,249,95,73,222,222,55,149,3,98,58,82,84,48,152,220,
193,37,109,228,42,118,8,244,3,53,151,175>>
Have true
```
> Bump blessed snapshot to height 435601

- rebar.lock
- test/miner_state_channel_SUITE.erl
Core PR: https://github.com/helium/blockchain-core/pull/550
Confirmed resync with validation from height: 434161 (just before first sc_v2 activation).
> Updates for state channel causality fixes

- config/sys.config
```
Height 447121
Hash <<160,141,55,78,69,39,150,232,108,56,181,151,211,7,186,195,136,110,22,196,
93,188,49,154,239,36,35,63,91,230,193,165>>
Have true
```
> Bump blessed snapshot to height 447121

- .buildkite/scripts/.dockerignore
- .buildkite/scripts/Dockerfile-amd64
- .buildkite/scripts/Dockerfile-arm64
The Docker image build fails if no `_build` directory already exists. Instead of `RUN rm -rf _build` the best practice according to those in the know is to add a `.dockerignore` file with `_build` in it.
> Add .dockerignore with _build directory

- src/miner_hbbft_sidecar.erl
i think that a lot of the time issues we're seeing are coming from certain receipts becoming too large to validate in a timely fashion, so this puts much tighter restrictions on them.
> add per-type timeouts to txns

- config/sys.config
```
{blessed_snapshot_block_height, 468001},
{blessed_snapshot_block_hash,
<<95,32,115,49,202,178,187,168,47,197,110,73,170,17,213,253,19,173,75,59,
150,7,36,225,225,85,172,60,157,146,4,241>>},
```
> Bump blessed snapshot to 468001

- config/sys.config
- src/miner_keys.erl
The Blackspots that RAK is manufacturing for the Helium Network will come with a version 4 UUID written to an `onboarding_key` file on the boot partition of the microSD card.
```
blackspot
e8d57c09f96c41229ff34f8889504a05
{pubkey,"11k4Gn6Qhs6JDet1w1fKxUe647zw4KRiZCYhNBtqYCL16BNmjRo"}.
{onboarding_key,"e8d57c09f96c41229ff34f8889504a05"}.
{animal_name,"decent-tortilla-bee"}.
```
Notice that the `onboarding_key` displayed for a Blackspot is no longer `undefined` when a `/mnt/uboot/onboarding_key` file exists.
> Read onboarding_key from file on Blackspots

- config/sys.config
```
Height 475921
Hash <<208,73,146,223,228,71,202,161,17,246,111,134,211,250,40,85,129,245,112,
48,151,57,190,37,114,145,157,225,194,38,1,183>>
Have true
```
> Bump blessed snapshot to height 475921

- config/sys.config
- src/miner_app.erl
it's sometimes hard to tell when a node reboots on hotspots, so use the lager pterm feature to cache the os pid for inclusion in the logs.
> upgrade lager, use new pterm feature to include os pid

- config/sys.config
- rebar.lock
```
Height 499681
Hash <<4,171,167,134,123,207,42,239,46,240,121,72,154,56,75,108,198,45,134,40,
252,107,219,206,219,31,38,163,9,244,31,179>>
Have true
```
> Bump blessed snapshot to height 499681

- audit/var-45.md
- src/poc/miner_onion_server.erl
As Proof of Coverage onion packets are variable in size (based on the path length), we should dynamically select the correct spreading factor based on the packet size to ensure compliance with the LoRaWAN specification and any regional regulations.
> Dynamically select spreading factor for PoC packets

- .buildkite/scripts/make_image.sh
Docker has a `latest` tag that is generally applied to repositories for the latest "GA" image. Community has been asking for this in some shape or form. I am thinking of PastaGringo in particular and @jamiew today exclaimed: "My kingdom for a ‘latest’ tag on quay".  Indeed, it would greatly simplify [scripts ](https://github.com/Wheaties466/helium_miner_scripts) meant to keep the service up to date.
In our case, our repository has Dockers for two architectures and so simply `latest` will not do. 
We could 
- split the repository, such that `https://quay.io/repository/team-helium/miner-amd64` and `https://quay.io/repository/team-helium/miner-arm64` exist
- append the architecture to the `latest` tag, such that tags `latest-amd64` and `latest-arm64` exist
The latter is less work, thus it is …
> Add a Docker Tag for latest-arch

- src/poc/miner_onion_server.erl
This PR adds on to #521 by adding additional EU868 specific datarates for PoC, based on the guidance from Semtech here: https://lora-developers.semtech.com/library/tech-papers-and-guides/the-book/packet-size-considerations/
> Add EU868 specific datarates for PoC packets

- config/sys.config
- src/miner.erl
While the current system draws neat curves, there's no inherent momentum to the system.  As such, we should move to a system that catches up at maximum speed until the final trim adjustments, which are made a minimum speed to prevent large time oscillations around the target time.
> reduce the time period, be more aggressive about catchup

- config/sys.config
bump snapshot to `535681`
```Height 535681
Hash <<78,48,67,4,49,161,46,53,135,40,254,219,250,62,224,61,252,95,27,134,93,
96,89,83,54,231,26,124,214,197,101,246>>
Have false
```
> Bump blessed snapshot

- src/miner_lora.erl
GWMP V2 moves `rssi` and `lsnr` to new subobject named `rsig`.  This PR replaces `map:get` for those two fields with accessors.
Name |  Type  | Function
:------:|:------:|--------------------------------------------------------------
ant     | number | Antenna number on which signal has been received
chan    | number | (unsigned integer) Concentrator "IF" channel used for RX
rssic   | number | (signed integer) RSSI in dBm of the channel (1 dB precision)
rssis   | number | (signed integer) RSSI in dBm of the signal (1 dB precision)
rssisd  | number | (unsigned integer) Standard deviation of RSSI during preamble
lsnr    | number | (signed float) Lora SNR ratio in dB (0.1 dB precision)
etime   | string | Encrypted 'main' fine timestamp, ns precision [0..999999999]
foff    | number | …
> Handle GWMP (Semtech UDP protocol) V2 messages

- rebar.lock
- src/handlers/miner_dkg_handler.erl
- src/miner_consensus_mgr.erl
Instead of doing a gen_server:call and blocking on the reply, do a
gen_server cast and wait for a `mark_done` event to come back so we know
we've handed the key off. To make this work without sending duplicate
election_done messages to the consensus manager we track whether the
election done was acknowleded with a seperate record field.
This PR also attempts to improve the logging slightly to include
election delay adjacent to the election height more consistently and it
also tries to improve the group cancel behaviour.
> Make election_done asynchronous to avoid mutual blocking consensus mgr

- config/test.config
- rebar.config
- rebar.lock
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
support for https://github.com/helium/blockchain-core/pull/526
> add test for multikeys

- config/sys.config
- rebar.lock
```Height 555121
Hash <<5,98,107,54,176,67,254,172,144,204,163,3,210,16,38,245,223,88,236,19,
229,129,67,171,84,0,132,61,122,60,164,82>>
Have true
```
> Update blockchain-core and bump snap

- priv/countries_reg_domains.csv
Currently undefined, meaning that Hotspots in the Ukraine cannot participate in PoC or anything LoRa related. This adds EU868 as the correct region.
> Add EU868 region for UA

- src/miner_lora.erl
In addition to the fixes in calls to `retry_with_rx2`, this PR first adds type specs to to ensure those calls are flagged. The second commit is the actual argument order fix.
This bug only rears its head when dowlinking @ RX1 fails. You can apply the following patch to ensure that happens.
```patch
diff --git a/src/miner_lora.erl b/src/miner_lora.erl
index 23d1a37..efeda79 100644
--- a/src/miner_lora.erl
+++ b/src/miner_lora.erl
@@ -770,7 +770,9 @@ send_packet(Payload, When, ChannelSelectorFun, DataRate, Power, IPol, HlmPacket,
end,
Token = mk_token(Timers),
-            Packet = create_packet(Payload, When, LocalFreq, DataRate, Power, IPol, Token),
+            NewWhen = When - 5000000,
+            lager:warning("Adjusting When from ~p down to ~p", [When, NewWhen]),
+            Packet …
```
> Fix argument order in calls to retry_with_rx2

- config/sys.config
- rebar.lock
```Height 560881
Hash <<69,17,78,79,33,60,213,229,142,128,199,64,90,53,181,248,164,254,58,151,
144,219,186,45,113,138,183,54,140,247,130,123>>
Have true
```
> Update blockchain-core and snapshot to 560881

- rebar.lock
- run.sh
- src/cli/miner_cli_genesis.erl
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
support for https://github.com/helium/blockchain-core/pull/676.
no code changes are actually required, but this changes the test defaults so these new paths are exercised, and twiddles a few things where it's important that we start on an earlier version.
> fix tests for election v4 stuff

- include/miner_util.hrl
- src/poc/miner_onion_handler.erl
- src/poc/miner_onion_server.erl
- src/poc/miner_poc_handler.erl
- src/poc/miner_poc_statem.erl
- test/miner_poc_SUITE.erl
In certain conditions we've seen that a single Hotspot is able to submit more
than one PoC receipts and witnesses per PoC layer (hop). While these receipts
are (correctly) filtered later, this PR fixes the underlying condition and and
only allows distinct P2P peers to report a witness/receipt per layer. This
should addresses this rare but concerning behaviour we've observed.
> Only allow one p2p address per layer

- src/miner.erl
With the current block time adjustment code, we never seem to get down to 60 second blocks.  This should make us get closer before we move to slow adjustments, which should let us average closer to 60s blocks.
> Make the "gentle nudge" period smaller

- src/poc/miner_onion_server.erl
Because PoC packets do not use the LoRaWAN protocol, we don't need to count those 13 bytes (or more) in the spreading factor calculations.
> Update spreading factor to account for no lorawan header

- config/sys.config
we've verified that snapshots are now working after the deployment of `2020.12.15.2`, and now we'll bump the snapshot to a working and recent one.
> update snap now that they're working again

- config/sys.config
- rebar.lock
```
Height 642961
Hash <<213,216,64,169,119,157,209,112,77,143,249,60,59,237,142,170,255,100,183,
105,232,58,104,10,134,30,63,135,140,222,211,65>>
Have true
```
Also updates core for [invalid witness reason](https://github.com/helium/blockchain-core/pull/706) support.
> Bump snap to 642961 and update core

- src/poc/miner_poc_statem.erl
Problem to solve: The current POC challenge interval only has about a 1-in-60 chance of triggering. This is too infrequent. Ideally challenges would scale against some kind of global setting, but that is future work.
Solution: Modify the jitter factor to make it easier to trigger challenges more frequently.
> Adjust the POC challenge jitter factor

- config/sys.config
```
./_build/dev/rel/miner/bin/miner snapshot list
Height 653041
Hash <<157,193,26,18,133,11,28,6,94,75,124,63,106,13,247,88,191,177,55,183,136,
225,21,167,52,218,223,255,61,103,114,73>>
Have true
```
> Bump snapshot to 653041

- src/poc/miner_poc_statem.erl
This stops including a witness which is the challengee itself at the time of poc receipt txn construction once all the layer responses have been gathered.
> Fix poc statem to disallow self witnessing

- src/miner_keys.erl
This changes makes the onboarding key the same as the public key of the hotspot, but only if there is not already an onboarding key present.
Fixes #594
> Make onboarding key pubkey

- config/sys.config
- rebar.lock
~~TODO: Update core sha once https://github.com/helium/blockchain-core/pull/721 lands~~
> Update snapshot to 687601 and bump core

- src/handlers/miner_hbbft_handler.erl
this is causing occasional consensus manager crashes and problems for block times.
> ignore mark_done in the hbbft handler

- src/cli/miner_cli_info.erl
There was missing "info" in the display. Made it look like the other commands such as peer.
Also made it more clear for what info_in_consensus_usage(), and info_name_usage() does.
Added the region to the info_usage(). Was missing in the past.
These are all just small changes, no changes to the base codebase, only to the UI of the CLI interface for the miners.
> Useablity improvments to miner info commands

- src/miner_lora.erl
SX1302's use the `rssis` field from the packet forwarder to denote the strength of the signal, versus `rssi` which is the strength of the *channel*. SX1302 `rssis` appears to be behave like SX1301 `rssi`, so this update uses `rssis` if available.
> Update packet_rssi function to use RSSIS if available

- src/miner_lora.erl
Reverts helium/miner#624
This probably need re-characterized acceptance curves to happen first.
> Revert "Update packet_rssi function to use RSSIS if available"

- config/docker-val.config
The miner docker release has the log files in the mapped data dir, which makes tailing and dealing with them slightly more convenient. this is just a change to do the same for the validator docker release.
fixes #666
> For docker val, move log files to the data dir

- config/sys.config
This PR is an attempt to reduce the frequency of errors that https://github.com/helium/relcast/pull/42 attempts to handle. Increasing [`max_write_buffer_number`] has the effect of increasing `max_write_buffer_size_to_maintain`:
```c++
// Default:
// If using a TransactionDB/OptimisticTransactionDB, the default value will
// be set to the value of 'max_write_buffer_number * write_buffer_size'
// if it is not explicitly set by the user.  Otherwise, the default is 0.
int64_t max_write_buffer_size_to_maintain = 0;
```
I believe this PR is low-risk, and I'm purposely conservatively bumping the value by quantity 2 instead of going to the next power of two. However, fine tuning these values require in depth knowledge and profiling of an application's RocksDB usage.
[`max_write_buffer_number`]: …
> Bump rocksdb buffers

- rebar.config
- rebar.lock
We've been pulling in a branch of longfi for a long time which just got merged. This new tag tag also adds a commit by @ke6jjj that fixes BSD builds.
> Bump longfi to 0.2.0

- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
- test/miner_packet_routing_SUITE.erl
- test/miner_payment_txn_SUITE.erl
- test/miner_payment_v2_txn_SUITE.erl
- test/miner_reward_SUITE.erl
- test/miner_router_SUITE.erl
- test/miner_state_channel_SUITE.erl
- test/miner_transfer_hotspot_txn_SUITE.erl
- test/miner_txn_bundle_SUITE.erl
- test/miner_txn_mgr_SUITE.erl
This needs more work, but it appears to help if we crash while initting the testcase (end per testcase is not called, so the nodes are not stopped).
> WIP to clean up if init_per_testcase fails

- priv/countries_reg_domains.csv
Accidentally put EU868 for Uganda instead of IN865 as per the lora doc
Closes: #677 
Change-type: patch
Signed-off-by: Aaron Shaw <shawaj@gmail.com>
> frequency: update Uganda to correct frequency

- .buildkite/pipeline.yml
Problem to solve: Currently ARM64 docker images build with CPU emulation using QEMU which is very slow
Solution: Use a native ARM64 server to build these images
> Use arm64 build queues

- .buildkite/pipeline.yml
Problem to solve: We are currently building ARM64 docker images using QEMU. This is very very slow.
Solution: Use a native ARM64 build system to create the Docker image
> Use arm64 queue for arm docker builds

- config/sys.config
`helium-wallet` had a bug when generating swarm_keys when the previous swarm_key was being generated. This is a new swarm_key for the roaming router and has been tested.
> regenerate roaming router swarm_key

- src/miner_hbbft_sidecar.erl
Even with the fastest hotspots, txn volume is such that we're struggling to validate good election transactions before they time out.  This adjustment will give less time to overly expensive poc receipts and much more time to elections, which should allow them to succeed more often.
> give more time to consensus groups and less time to poc receipts

- config/sys.config
```
Height 888481
Hash <<81,247,174,136,61,127,118,100,11,194,97,73,108,106,246,158,242,78,155,
110,246,212,41,166,240,156,63,208,107,228,109,194>> (<<"51f7ae883d7f76640bc261496c6af69ef24e9b6ef6d429a6f09c3fd06be46dc2">>)
Have true
```
```
$ http get https://api.helium.io/v1/snapshots | jq '.data[0]'
{
"snapshot_hash": "UfeuiD1_dmQLwmFJbGr2nvJOm2721Cmm8Jw_0GvkbcI",
"block": 888481
}
```
> Update blessed snap to 888481

- config/sys.config
```
$ http get https://api.helium.io/v1/snapshots | jq '.data[0]'
{
"snapshot_hash": "E3QX2CuV2GXrbIg33aB07veCsVzsjX49RlK5lbmbtGs",
"block": 890641
}
```
```
Height 890641
Hash <<19,116,23,216,43,149,216,101,235,108,136,55,221,160,116,238,247,130,177,
92,236,141,126,61,70,82,185,149,185,155,180,107>> (<<"137417d82b95d865eb6c8837dda074eef782b15cec8d7e3d4652b995b99bb46b">>)
Have false
```
> Update snap to 890641

- src/cli/miner_cli_genesis.erl
- src/handlers/miner_dkg_penalty_handler.erl
- src/handlers/miner_hbbft_handler.erl
Problem: `miner_dkg_penalty_handler` is missing how to handle `tc_key_share:secret_key` [de]ser
Solution: 
- Add `tc_key_share` functions to `miner_dkg_penalty_handler`
- Furhter remove all references of `tpke` from miner src, however there's tpke in the lock file which we can remove once we consolidate the ultimate rebar.lock
- Also updated cli genesis make_vars for run.sh usage
Test:
- Confirmed run.sh works after stop/start a node in consensus locally
> Remove all tpke references

- rebar.lock
- src/handlers/miner_hbbft_handler.erl
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
The signature type defs and test helper snuck in because I wasn't able to force push fast-enough before #823 got merged.
TODO:
> Treat block opaquely instead of accessing directly

- src/miner_util.erl
Problem to solve: We currently do not collect any firmware release information from miners in their gossiped metadata. It would be a useful thing to know, especially when validators come online and we do not have the ability to inspect them.
Solution: Collect the firmware release info (if it exists in the expected spot and format)
> Extend metadata fun to gossip release info

- src/handlers/miner_hbbft_handler.erl
- src/miner.erl
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
we never time out a round, which means that if some critical messages are lost, we might never proceed.  This code adds time-based voting to skip.
todo: needs to be properly set on restore?
> add time-based skip voting

- src/miner.erl
Currently if we cannot agree on a BBA result vector we default to the
empty binary (all 0s). This results in *all* nodes taking a BBA penalty
hit. This is incorrect and this change defaults to the assumption that
everyone completed their BBA so that we do not penalize the entire
group.
This change may cause a "split block" but as long as it merges after the
time based autoskip it should be safe once enough nodes have upgraded.
> Fix BBA vote default to be everybody completed

- config/sys.config
- src/miner_val_heartbeat.erl
Switch heartbeat txn submission to check `validator_version` instead of `election_version`
> Switch heartbeat txn submission to check validator_version

- src/handlers/miner_hbbft_handler.erl
- src/miner.erl
since this change can be unsafe, we need to guard it behind a var so everyone switches at the same time.
> guard default change

- config/docker-testval.config.src
- config/docker-val.config.src
- config/sys.config
- config/test_val.config.src
- config/val.config.src
- change late block time to 15 minutes, rather than 150 (typo fix)
- increase block sync sizes on validators
- allow more incoming connections on validators
> validator reconfigure

- .buildkite/scripts/Dockerfile-amd64
- .buildkite/scripts/Dockerfile-arm64
- .buildkite/scripts/Dockerfile-testval-amd64
- .buildkite/scripts/Dockerfile-testval-arm64
- .buildkite/scripts/Dockerfile-val-amd64
- .buildkite/scripts/Dockerfile-val-arm64
- .buildkite/scripts/make_deb.sh
Problems to solve: The Dockerfiles used to build images should expose the internal ports (even though docker still requires you to use `-p` to publish the ports when the container is started) Also we want to standardize on the location of the genesis block download. Finally the validator tag gets mangled by an incomplete regex.
> Expose ports, pull genesis from S3, fix deb name

- config/sys.config
- rebar.lock
- src/miner_ecc_worker.erl
- src/miner_keys.erl
- src/miner_sup.erl
This PR adds two new options to the ECC section of the configuration file:
* `bus` allows configuring the I2C bus and defaults to `i2c-1`
* `address` allows configuring the I2C address and defaults to `0x60`
:warning: This PR depends on https://github.com/helium/ecc508/pull/9 ~and does not (yet) update the `rebar.lock` accordingly.~
> Allow configuring ECC I2C bus & address

- config/docker-testval.config.src
- config/docker-val.config.src
- config/docker.config
Fix for #882. If bond to 127.0.0.1, this will only listen within a docker container making it inaccessible.
> Bind JSONRPC to 0.0.0.0 for docker

- rebar.config
- rebar.lock
Also, change `rebar.config` dev profile to correctly compile and build a devrelease (this was broken on miner:master because relx hates it)
> Update ecc508 dep

- src/miner_keys.erl
Not sure if:
- `address` type is restrictive-enough - can it be 0? less than 0?
- `undefined` is a possible value for each
> Fix missing key_info fields

- config/sys.config
- src/miner_util.erl
it'd be nice to be able to bias the entire  fleet towards gossiping with the validators (as miners never generate blocks now) 
requires: https://github.com/helium/erlang-libp2p/pull/364
> add random peer predicate

- config/docker-val.config.src
- config/sys.config
- config/val.config.src
we don't fully trust this snap, and will only apply it to non-consensus nodes until the chain has generated a new snap.
> bump to new snap for miner, exclude validators

- .buildkite/scripts/Dockerfile-amd64
- .buildkite/scripts/Dockerfile-arm64
A recent change caused the JSONRPC and GRPC ports to be exposed by docker by default, while these shouldn't be exposed on miners.
> Do not expose the JSONRPC and GRPC ports on the miner docker files

- src/handlers/miner_hbbft_handler.erl
- src/miner.erl
If a node does not get its proposal into a round have it start the next
round early to get a jump on things. This should help with cases where
the node is behind and, because it has to validate all the blocks it
didn't sign, can't catch up for the whole epoch.
> Start next round early if node does not have its proposal in

- src/cli/miner_cli_hbbft.erl
- src/jsonrpc/miner_jsonrpc_hbbft.erl
- src/miner_util.erl
Implement the `hbbft_perf` for JSON/RPC use, as requested in
helium/miner #873.
A large portion of this code originally lived entirely within
`miner_cli_hbbft.erl`, so rather than duplicate it, the essential
information gathering now happens in `miner_util.erl` (per Evan's
suggestion) and is then parsed and formatted in different ways
by the CLI (`miner_cli_hbbft.erl`) and the JSON/RPC handler
(`miner_jsronrpc_hbbft.erl`).
This is a cherry-pick commit to rescue a branch that has been
screwed up by a bad rebase/merge.
> Implement hbbft_perf for JSONRPC.

- src/miner_ebus.erl
```
root@klk-wifc-030270:~ # dbus-send --system --print-reply --reply-timeout=120000 --dest=com.helium.Miner / com.helium.Miner.BlockAge
method return time=1626454711.232803 sender=:1.201 -> destination=:1.203 serial=4 reply_serial=2
int32 174
```
> add block age dbus endpoint

- src/jsonrpc/miner_jsonrpc_ledger.erl
The endpoint `ledger_validators` returns information about all currently-staked validators. This adds the ability to query a specific validator, if desired.
> Implement ability to query stats for a single validator.

- src/jsonrpc/miner_jsonrpc_dkg.erl
- src/jsonrpc/miner_jsonrpc_hbbft.erl
- src/jsonrpc/miner_jsonrpc_info.erl
- src/jsonrpc/miner_jsonrpc_ledger.erl
- src/jsonrpc/miner_jsonrpc_sc.erl
- src/jsonrpc/miner_jsonrpc_snapshot.erl
- src/jsonrpc/miner_jsonrpc_txn.erl
Clean up the JSON/RPC API results so that conditional states, missing data
and errors are all easier to detect programmatically. General principles:
* When there is an error, make sure to consistenly use the `?jsonrpc_error()`
macro.
* If a value is semantically boolean, make it so in the result set. Don't
return a string.
* If there's no particular error in a query, but there's no data for an item
then try to use `null` instead of a specialized strings such as "undefined".
* If a query only returns data if the validator/miner is in a specific mode,
try to ensure that there is a consistently available attribute that
can be checked _first_ in the result set. Don't make clients try to guess
the state by checking for the existence of other items, or even worse,
by checking the returned …
> Clean up JSON/RPC API for proper use of errors and data types.

- config/sys.config
Problem to solve: There wasn't enough room to include the 4th new seed node (`/ip4/3.34.61.168/tcp/2154`) in the TXT DNS record. We want to include it in the overall list though.
Solution: Hardcode it in the configuration file
> Add new hardcoded seed node

- config/test.config
Setting jsonrpc port 0 for being able to do local `run.sh`, otherwise you run into some `eaddrinuse` errors and none but one test miners boot.
> Port 0 for jsonrpc in test config for run.sh

- src/miner.erl
the current "connected" gives users the impression that they're not connected to anything at all.
This PR adds a session count, and changes the verbiage to "well-connected" when the user is connected to more than half of their target connection count.
closes #862
> clarify intention of 'connected' metric in session info

- src/miner.erl
The new fast-then-slow strategy of adjustments is interacting badly with the limited lookback period, leading to unwanted oscillations in block times.  Historically, we mostly only have slow blocks; it's possible that any positive period adjustment that exists on the chain is due to these sorts of windowing effects.
This PR limits the amount of negative catchup that we allow ourselves, to acknowledge that we're mostly reacting to slow blocks, and after a smoothing period or two should get us to a place of more regular block times.
> sharply limit the amount of negative catchup possible

- README.md
As far as I can tell, the 'run a miner' content in docs is gone. I'd be happy to be proven wrong.
Proposing removing the whole block instead of pointing to the gateway-rs guides. It could be nice to reference quay builds in this doc, but it can balloon into a bigger discussion around packet forwarders, etc.
Also took the opportunity to do a little formatting cleanup.
EDIT: Rendered view https://github.com/helium/miner/blob/174f5a692c66dc9ced7eeea1d73398ab97508a7a/README.md
> Readme cleanup, remove link to dead doc.

- config/sys.config
Replace the OG seed nodes with new static seed nodes controlled by ansible
> New static seed node IPs

- src/jsonrpc/miner_jsonrpc_peer.erl
Call would error out with a provided address, only `self` and `all` were working before.
> Fixing peer_book RPC call provided with p2p address

- src/cli/miner_cli_hbbft.erl
- src/jsonrpc/miner_jsonrpc_hbbft.erl
- src/miner_util.erl
Refactor and clean up miner_util:hbbft_perf/0 so that it returns a map, rather than a giant tuple, and rename some of its internal
variables so that they are easier to understand (e.g. "Start0" is now "ElectionStart").
Also clean up the JSON/RPC and the CLI `hbbft perf` endpoints as well.
(Same as #936 but squashed into 1 commit with minor formatting changes)
> Refactor hbbft_perf, renaming some confusing variables.

- config/sys.config
Adds European router to `default_router` while also providing entry in `node_aliases`. Can revert the `node_alias` entry if necessary, but would rather test it on a different effort.
> European Router

- src/poc/miner_onion_server.erl
Fix a bug that crept in when LoRa region information became more dynamic at runtime: consult the actual channel list size before trying to pick a random element from it, rather than assuming it is exactly 8 elements long.
This is @Vagabond 's patch from Discord on 2021-06-30.
Should fix #1037.
> Fix PoC transmission channel selection logic.

- .buildkite/scripts/make_image.sh
Problem to solve: When refactoring the script that drives Docker builds, the `$DOCKER_NAME` was inadvertently duplicated twice which led to duplicated tags on the `miner` build target.
> Inadvertantly duplicated DOCKER_NAME

- src/miner_discovery_worker.erl
It's possible, though usually rare, that the request to transmit a discovery mode beacon packet might time out. When this happens, make sure not to crash the entire discovery mode session but simply move on to the next packet.
Should fix #1058, discovered by @maco2035
> Handle discovery mode packet forwarder tx timeout more gracefully.

- src/miner_lora.erl
Reported stacktrace:
```erlang
2021-09-15 03:06:09.564 1 [info] <0.1159.0>@Undefined:Undefined:Undefined Application miner exited with reason: {{shutdown,
{failed_to_start_child,miner_restart_sup,{shutdown,{failed_to_start_child,miner_lora,{badarg,[{ets,lookup,[country_freq_data,
<<"US">>],[]},{miner_lora,reg_domain_data_for_countrycode,1,[{file,"miner_lora.erl"},{line,198}]},
{miner_lora,maybe_update_reg_data,1,[{file,"miner_lora.erl"},{line,907}]},{miner_lora,update_state_using_chain,2,
[{file,"miner_lora.erl"},{line,277}]},{miner_lora,init,1,[{file,"miner_lora.erl"},{line,271}]},{gen_server,init_it,2,[{file,"gen_server.erl"},
{line,...}]},...]}}}}},...}
2021-09-15 03:06:09.645 1 [warning] <0.1498.0>@libp2p_group_gossip_server:handle_cast:241 gossip handler libp2p_peerbook 
failed to …
```
> Possible patch for failing region lookup

- rebar.lock
- src/miner_hbbft_sidecar.erl
- test/miner_ct_utils.erl
- test/miner_txn_mgr_SUITE.erl
Which expects a node's height to be passed along with the transaction acceptance status.
Pre-merge TODO:
> Handle and test transaction protocol v2

- src/jsonrpc/miner_jsonrpc_info.erl
- src/jsonrpc/miner_jsonrpc_ledger.erl
Adds gain and elevation to jsonrpc info_summary call and adjusts the verbose ledger format to also use the /10 version
Fixes: #1048 (jsonrpc only)
> Adjust gain to float and add to summary

- .buildkite/scripts/make_image.sh
- Dockerfile
Problem to solve: Builds that use _GA tags fail because of the discrepancy between the version without `_GA` and the version relx pulls from git. We also need to make it easier for manufacturers to overlay their own config file(s) without having to navigate the release directory structure in the image.
Solution: Stop stripping `_GA` and only update the tags of docker images. Add a synlink from `/config` to the proper release directory.
> Fix GA image building

- rebar.config
Problem to solve: 2.8.0 is a pretty old release of jsx. We are using 3.1.0 in core.
Solution: match the definition in core
> Bump jsx dep to match core

- src/poc/miner_poc_statem.erl
- test/miner_poc_v11_vars.hrl
The core developers have noticed some cases where some witness receipts are coming from gateways that don't match the signed witness message. This branch fixes this cases where this shouldn't happen. 
This also fixes a (now) stale URL for PoC-v11 tests.
> Fix witness check to ensure that addrs match

- rebar.lock
Another bump for https://github.com/helium/blockchain-core/pull/1070 and https://github.com/helium/blockchain-core/pull/1069
> Bump core for core#1069, core#1070

- src/jsonrpc/miner_jsonrpc_ledger.erl
Add a JSON-RPC endpoint for querying LoRa region parameters to support manufacturer integration with PoC v11's dynamic (on-chain) region parameterization.
> Add a JSON-RPC query for LoRa region params.

- src/jsonrpc/miner_jsonrpc_ledger.erl
LoRa region parameters are stored on chain using integers where possible. This extends to EIRP limits, which are stored in a unit that can rightly be called a "centiBel" or "one hundredth of a Bel". Such a unit does indeed exist, but it's obscure and just going to cause problems:
> What is the meaning of cbm here? Or is this a typo and should it be dbm? 
So convert the on-chain value to its more widely understood relative: the deciBel.
> Use dBm, not cBm, for EIRP results. More widely understood.

- src/miner_lora.erl
Problem
----
Alpha hotspots are failing to boot `miner_lora` because of a missing catch-all clause with error:
```
2021-11-05 00:16:33.108 25239 [error] <0.1463.0>@Undefined:Undefined:Undefined Supervisor miner_sup had child miner_restart_sup started with miner_restart_sup:start_link(#Fun<miner_keys.1.127700184>, #Fun<miner_keys.0.127700184>) at undefined exit with reason {shutdown,{failed_to_start_child,miner_lora,{{case_clause,{ok,10}},[{miner_lora,reg_domain_data_for_addr,2,[{file,"miner_lora.erl"},{line,169}]},{miner_lora,maybe_update_reg_data,1,[{file,"miner_lora.erl"},{line,952}]},{miner_lora,update_state_
using_chain,2,[{file,"miner_lora.erl"},{line,291}]},{miner_lora,init,1,[{file,"miner_lora.erl"},{line,285}]},{gen_server,init_it,2,[{file,"gen_server.erl"},{line,374}]},{gen_server …
```
> Ignore all prior pocv11 lookups

- src/miner_lora.erl
`miner_lora` will send itself a message after 500ms to recalculate the regulatory domain when a chain variable transaction appears in a block.
> Recalculate regulatory domain on var txn

- config/docker-testval.config.src
- config/docker-val.config.src
- config/test_val.config.src
- config/val.config.src
there is no big perf gain to be had at 64MB, but it does incur substantial additional memory use, so adjust it downwards some.
> adjust sizes downward for global caches

- config/sys.config
Update the gossip version to 2 for all miners and validators.  This activates push gossip, see: https://github.com/helium/blockchain-core/pull/1023 for more details.
> update gossip version to 2

- src/miner_lora.erl
> Ignore lorawan packets that are too short to be valid

- .buildkite/pipeline.yml
- .buildkite/scripts/make_deb.sh
- .buildkite/scripts/make_image.sh
- .buildkite/scripts/packagecloud_upload.sh
There seem to be conflicts with concurrent tags being pushed to the miner repo that have caused miner and validator tags to be mixed up on validator images pushed to the public quay repo that need subsequent manual editing to correct. This change should lock in the version of the tag that triggered a build as the tag that gets applied to the images published.
> pass build trigger tag for image version

- .buildkite/pipeline.yml
The new `$VERSION_TAG` environment variable needs to be bound in the context of the docker image build script for non-validator builds as well.
> finish injecting new envar into docker build script

- src/miner_hbbft_sidecar.erl
Validation deadline timeouts are expected and not worth logging
> Reduces unknown ref response logs

- config/sys.config
Expands the available list of seed nodes miners can fall back to when DNS lookups fail, spreading the load of peerbook requests between 5 instead of the previous 3 nodes.
> expanding the blessed seed list

- config/sys.config
The DNS response from the seed nodes in the DNS pool is too large; to reduce the load of the lookup response size without losing processing power from the seed pool, we're transferring 3 nodes over to the static config list.
> transferring seed nodes from dns to sys.config static list

- .buildkite/pipeline.yml
This change aims to address the uncommon situation where a miner build needs to be re-run after additional tags that still match the `grep -v` filter are applied to the same SHA, causing the rebar issue where multi-tagged SHAs are unable to select the correct tag to set the application version.
Also explicitly calls up the SHA of the exact tag being built instead of relying on the HEAD argument pointing to the correct SHA in case additional fetches or other git manipulations go into the build process that could change that value from the SHA that triggered the build in the first place.
> explicitly calling up build tag sha and deleting all but the exact tag

- config/sys.config
We've observed extremely large rocksdb log files (1gb+) in the field. We
don't need or want the logs that large, so impose some size and time
rotation limits.
> Limit the size and age of rocksdb log files

- config/sys.config
- src/miner_lora.erl
Makes the currently hardcoded `https://api.helium.io/v1` API base URL configurable via `sys.config`. This allows using a different API server, effectively removing the pressure on the public, official API service.
> Allow for custom API base URL in sys.config

- src/miner_app.erl
It appears that setting `follow_mode` blockchain app env in dev.config (or other) has no effect because it gets explicitly overwritten in `miner_app.erl` specifically for miner in `gateway` mode.
This fixes it to honor app env and only default it when the app env is `undefined`.
> Honor follow_mode set in app env

- config/sys.config
Problem to solve: In #1267 we added a bunch of static seed nodes until helium/erlang-libp2p#405 was ready to merge. The libp2p PR implementing DNS pools has been merged.
Solution: We now need to remove those static seeds and set the seed config DNS name so that the seed DNS pools can be fetched.
> Pull seed node IPs from DNS pool

- .buildkite/hooks/post-checkout
In the event the buildkite host has any issues with its filesystem (rebuilds or whatnot), this prevents the loss of the the git tag deletion hook that causes so many issues with rebar3 release versioning
> persisting 'delete tags' hook so it survives

- .buildkite/hooks/post-checkout
Avoids weird edge case where the buildkite workspace _is_ in fact not fully cleaned between builds and the hook's `fetch --tags` command throws an error and crashes the build with an exit 1 when a fetched tag already exists on the host and would be "clobbered".
This was observed when running the "_GA" (i.e. retag Docker image) build job where the tag applied from the previous non-GA build is still present when the current run's post-checkout hook attempts to pull tags again.
> force fetching tags to avoid 'clobber existing tags' warning

- rebar.lock
Includes fix to remove spurious subscriptions to blockchain events for unary state channel gRPCs
https://github.com/helium/sibyl/commit/a4917b1a8e9b9476214951dca08de7694a1bbf6d
> bump sibyl

- src/jsonrpc/miner_jsonrpc_txn.erl
Fix issue #1118 by properly converting owner and payer addresses into the
format expected by `blockchain:add_gateway_txn` and `blockchain:assert_loc_txn`,
which expect addresses as Erlang B58 strings, not pre-parsed pubkey binaries.
> Fix JSONRPC B58 translations for gateway txns.

- .buildkite/scripts/make_image.sh
- Dockerfile
Upgrading dockerized versions of Miner/Validator to default to OTP 24. Also removes libgcc from the build which appears to be unnecessary after comparing to the blockchain-http build.
> Updating default OTP versions for dockerized miner/validator builds

- .dockerignore
Avoiding copying additional unnecessary directories from the source directory into the docker build context
> removing add'l directories from dockerignore

- src/miner_lora.erl
Fix an issue which was preventing the use of the "rssis" signal report
on a packet, even when it was present and desired. RSSIS or "RSSI of signal"
is an additional packet meta-data item provided by the SX1302 (and other)
packet forwarders, and when present, it more accurately reflects the power
level at which a packet was received. In contrast, the "rssi" value on such
forwarders reflects the "RSSI of channel", which is closer to the RSSI of the
channel noise floor, not the packet that was received.
Since "rssis" is a more accurate gauge of reception power, it is preferred
by PoC v11, but wasn't actually being used because of this issue.
Based on an original commit by Amir Haleem.
> Fix an issue which was preventing use of RSSIS when available.

- config/dev.config
- config/docker-testval.config.src
- config/docker-val.config.src
- config/test_val.config.src
- config/val.config.src
- rebar.lock
for time stabilization, we should keep more blocks on validators, + disable on dev nodes.
> bump core, protect more blocks from gc

- config/docker-val.config.src
- config/val.config.src
When in consensus group, validators seem to hit up against the default max tcp connection limit of 1024. This PR updates the default configuration for validators to increase the max to 2048. 
The screen shot below shows a validator in CG for 6 rounds. Connections grow over time until they are clipped at 1024 around the 3rd or 4th round. I have observed this on multiple validators and multiple CG tenures. This may be exacerbated by https://github.com/helium/erlang-libp2p/issues/419.
> Increase validator max tcp connections

- src/jsonrpc/miner_jsonrpc_txn.erl
Fix an issue where optional parameters to the JSONRPC methods `txn_add_gateway` and `txn_assert_location` weren't being picked up when provided.
> Fix #1377 and other JSONRPC related parameter issues.

- .buildkite/scripts/make_image.sh
Problem to solve: We want to publish and update `alpha-$ARCH` and `beta-$ARCH` tags on quay (our docker registry) to support miner test images on our test hotspot fleet.
Solution: Look for `_alpha` or `_beta` on Git Hub tags and then update an image appropriately on quay.
> Enable _alpha, _beta tags on docker registry

- rebar.lock
Includes a fix to blockchain-core that prevented snaps from loading when the snapshot_info had not yet been defined for the miner, as well as handling response headers that track the version of the snap info available on s3 via etags
> updating blockchain to address bug in snap loading

- config/docker.config
The current poc_denylist worker is deployed but not configured in all miner releases. This configuration change will enable the denylist worker to kick off and start running in releases produced with the docker rebar profile, leaving other releases disabled by default.
> configuring new denylist on docker release profile

- config/aws.config
- config/dev.config
- config/docker-testval.config.src
- config/docker-val.config.src
- config/docker.config
- config/seed.config
- config/sys.config
- config/test.config
- config/test_val.config.src
- config/val.config.src
We need to be able to carry the new denylist configs into firmware builds that overwrite the `docker.config` file since this behavior needs to be the default for any dockerized miner that _doesn't_ explicitly want to disable it by mounting a custom config over the one that ships with the image.
This change moves the denylist miner application configs into the default sys.config file and then explicitly disables it in the non-miner config profiles.
> default denylist in sysconfig, disable explicitly

- .buildkite/scripts/make_image.sh
Ensure docker tag builds triggered by a `_GA` git tag carry into the docker artifact pushed to the quay registry for makers that trigger deployments and/or releases based on explicit GA'd semvers instead of a floating `latest` tag release.
Addresses issue #1409
> preserving and pushing _GA-suffixed tags

- .buildkite/pipeline.yml
- .buildkite/scripts/make_image.sh
When building a non-validator tag ending with "_testnet":
- set "NET_TYPE" to "testnet"
- set image registry to quay.io/team-helium/testnet
- strip "_testnet" from the version since it's going to a different registry
I pushed the tag `2022.02.09.0_PR1427_testnet`, iﬀ: 
-  [ ] with the image name `2022.02.09.0_PR1427` (1) 
then everything worked correctly.
1: note the lack of `_testnet` in the image name
[build]: https://buildkite.com/helium/miner/builds?branch=2022.02.09.0_PR1427_testnet
[`team-helium/testnet`]: https://quay.io/repository/team-helium/testnet?tab=tags
[`team-helium/miner`]: https://quay.io/repository/team-helium/miner?tab=tags
> CI: special-case git tags ending with "_testnet"

- src/jsonrpc/miner_jsonrpc_txn.erl
instead of returning one since that’s what the caller would do also
> Fixes parse_integer to throw an error

- .buildkite/pipeline.yml
- .buildkite/scripts/make_image.sh
- rebar.config
This PR declutters image registries by keeping testnet builds out of them. The tagging scheme is as follows:
<table><thead><tr><th>Example Tag</th><th>Registry</th></tr></thead><tbody><tr><td>2022.02.23.0</td><td>quay.io/team-helium/miner</td></tr><tr><td>testnet_2022.02.23.0</td><td>quay.io/team-helium/miner-testnet</td></tr><tr><td>validator1.8.0</td><td>quay.io/team-helium/validator</td></tr><tr><td>testnet_validator0.1.99<br></td><td>quay.io/team-helium/validator-testnet</td></tr></tbody></table>
> Send _testnet tagged image builds to corresponding [validator,miner]-testnet Quay registries

- src/miner_hbbft_sidecar.erl
- src/miner_keys.erl
- test/miner_ct_utils.erl
- test/miner_payment_txn_SUITE.erl
- test/miner_txn_mgr_SUITE.erl
PaymentV2 testing additions validate that enforcing a block_size_limit chain variable drops the byte_size of serialized txns and txns continue to flow into subsequent blocks when they are not able to fit into a block.
Also validates and enforces that txns that are too big to ever be serialized to a size that will fit within the given limit are rejected in the hbbft_sidecar process submitting txns to the consensus group so they don't clog up the submission queue.
> Validating block_size_limit enforces manageable block txn sizes

- scripts/extensions/authorize
- scripts/extensions/dkg
- scripts/extensions/genesis
- scripts/extensions/hbbft
- scripts/extensions/info
- scripts/extensions/print_keys
Problem to solve: We are tired of getting relx timeout errors from the command line.
Solution: Set the timeout value to something really big.
(See also https://github.com/helium/blockchain-core/pull/1268)
> Set relx rpc timeout to 900 seconds

- gen_reset.sh
- src/cli/miner_cli_genesis.erl
Adds CLI and associated helper scripts to export the ledger data to a batch of gen txns, which can then be loaded and used as part of an initial dkg.  Allows a test network such as testnet to be reset whilst maintaining existing data.
Exported data includes accounts, gateways, validators, oracle price & chainvars.
Tested on a local chain via run.sh
> add genesis recreate cli

- src/miner_critical_sup.erl
- src/miner_keys.erl
minor changes to make the tpm branch configuration compliant with the current process supervision tree/startup where the `miner_critical_sup` is defining and starting erlang-based crypto signing workers if the embedded gateway is _not_ enabled (`miner_ecc_worker` and `miner_tpm_worker`) and ensuring the return value of `miner_keys:keys/0` matches what the critical supervisor needs to start the worker correctly.
> passing tpm key_path to worker; ensuring started

- Makefile
- src/miner_gateway_ecc_worker.erl
- src/miner_gateway_port.erl
- test/miner_gateway_mux_integration_SUITE.erl
The http_connection pid started by the grpc_client library is currently not monitored in any way by the gateway ecc worker process beyond including it in the connection record returned when establishing the connection. In the event the process exits, the ecc worker has no indication that its connection is gone and all subsequent attempts to establish a connection stream will fail.
This change monitors the connection process and attempts to clean up the remainder of the old connection before reconnecting as soon as the old pid is lost.
This change also adds the new `--stdin` flag expected by the latest release of the embedded gateway-rs.
> monitoring and testing gateway grpc pid

- config/docker.config
- config/sys.config
- priv/gateway_rs/settings.toml
- src/miner_gateway_ecc_worker.erl
- src/miner_gateway_port.erl
- src/miner_port_services_sup.erl
- src/miner_restart_sup.erl
- test/miner_gateway_mux_integration_SUITE.erl
Makes it easier for drop-in replacement and update of settings (such as moving from mainnet to testnet or vice versa) by reducing the number of sys.config changes needed to configure the different settings and process trees within the miner.
By consolidating all of the possible variations of a UDP listener to derive their configuration from the existing `miner, radio_device` application env key, the "public interface" for configuring the miner's listener remains the same.
> Consolidate udp listener port config under radio_device

- src/poc/miner_poc_denylist.erl
Bug proof in this log line:
```
2022-03-15 02:28:31.311 1 [info] <0.1844.0>@miner_poc_denylist:handle_info:{109,29} FORMAT ERROR: "new denylist version appeared: ~s have ~s" [2022031101,0]
```
Terms are integers, not strings.
> Fix format error.

- config/dev.config
- config/docker-testnet.config
- config/docker-testval.config.src
- config/docker-val.config.src
- config/docker.config
- config/seed.config
- config/sys.config
- config/test_val.config.src
- config/val.config.src
move the config that disables the embedded rust gateway and udp multiplexer back to the default sysconfig file. this has two advantages:
1. cleaner config; no longer needed to disable explicitly on all other profiles when it is enabled or undefined in the base config
2. allow enabling the config for specific release profiles so it does not need to be overridden _again_ at the firmware level (but still can be as needed)
This is needed most immediately to enable easier configuration of hotspots on the testnet where the bulk of testing the latest grpc-based communication between the components of the network will be taking place
> default disable embedded rust gateway and mux

- Makefile
The latest tagged version of the semtech-udp mux handles additional error parsing (warnings with tx_power value)
> update the mux version to 0.9.2

- .buildkite/scripts/make_deb.sh
Problem to solve: An .app file is missing during builds sometimes and this causes rebar3 to fail, which causes a build failure which isn't easily recoverable in the context of buildkite.
Solution: Enable rebar diagnostics during debian builds; handle rebar3 failure and allow retries at a build
> Output rebar diagnostics; retry on rebar fails

- .gitignore
- Makefile
- src/miner_gateway_port.erl
- src/miner_mux_port.erl
There is currently a situation where the rust gateway could crash after reconnect but before the managing port has exited the reconnect function so it never receives the next `'DOWN'` message. In this case, the port should attempt to reconnect a number of times and then return an error, which should result in the process crashing and being restarted, which should clear the (likely) transient problem preventing restart of the gateway.
> don't loop forever trying to reconnect to gateway

- src/handlers/miner_hbbft_handler.erl
i noticed this during general review that the relatively recent shift to sort PoC txns down-list in priority was not going to hold when poc_receipts_v2 became the normal for the network after the shift to poc-over-grpc. this small change should continue the sorting of txns fee buffer as adopted in https://github.com/helium/miner/pull/1399.
> sort v2 receipts as with v1 receipts

- src/poc/miner_poc_mgr.erl
within the new miner_poc_mgr, this change allows the validator preparing a challenge to filter out target miners that are present on the denylist and avoid generating challenges to them, as well as filtering out witness reports for them on receipt of witnesses
> checking challengees and witnesses against denylist

- src/miner_query.erl
these worked better when the blocks weren't 1mb+, update them to be a bit more memory efficient.
> for query don't pull entire blocklist into memory

- config/sys.config
requires https://github.com/helium/erlang-libp2p/pull/429 to not have a detrimental impact
> increase outbound gossip connections to 6 (3x)

- Dockerfile
the settings.toml file for the embedded rust gateway needs to be modified for the build network prior to taring up the release so it's copied into the correct directory when the final release is unpacked and then copied over to the runtime container image. in the previous version of this feature, we were modifying the file after the release had been packaged so by the time the settings config was concatenated together that gateway_rs priv directory in `/usr/src/miner` was being ignored by subsequent operations
> move gateway config concat to before release

- Makefile
In some situations, the gateway-rs dependency will cause a build failure because it attempts to checkout a commit in gateway-rs that is not present in the local clone. This change adds a git fetch prior to attempting the checkout to make sure that the latest commits are in the external/gateway-rs directory.
> Fix Makefile to fetch gateway-rs from repo before checkout

- src/miner_lora.erl
- src/miner_lora_light.erl
- src/poc/miner_poc_grpc_client_statem.erl
- test/miner_ct_utils.erl
- test/miner_gateway_mux_integration_SUITE.erl
adjustments to the miner_lora_light module to handle routing of packets in either the intended light mode when the light gateway is handling routing of non-poc lorawan packets as well as when the rust gateway is disabled but we're otherwise operating with the light version of the onion and lora servers
> handling non-poc packets in light mode w/o rust gw

- src/jsonrpc/miner_jsonrpc_peer.erl
- Fixes the Internal Server Error when using the `peer_refresh` jsonrpc method.
- Exposes the peer book count that is available using the cli via the jsonrpc method.
Fixes #1308
> Fix jsonrpc peer_refresh and add peer_book count

- config/test_val.config.src
- config/val.config.src
This PR adds environment variable replacement for additional configuration options commonly used by validator operators. 
As an added bonus, these templated vars will enable the elimination of the docker-specific sys.config.src templates. The docker differences that required separate sys.config.src files can be achieve using the with additional environment variables set in the image via the Dockerfile. I left that change for a separate PR.
A couple notes:
- Relx environment variable replacement drops double quotes (`"`) in strings, so I had to limit the replacement of `listen_addresses` to a single address instead of allow a list of addresses.
- I had to use an unconventional format for the `jsonrpc_ip` environment since curly brackets are a special character used by the replacement …
> Use env vars for common validator configs

- src/miner_critical_sup.erl
- src/miner_lora.erl
- src/miner_lora_light.erl
- src/miner_restart_sup.erl
- test/miner_ct_utils.erl
in the transitional phase where we are running under validator challenges/hotspots are no longer following the chain but we have not enabled the embedded gateway-rs packet router we will be using the `miner_lora_light` module to route lora packets received by the gateway. this change allows the correct / active lora module handling packets to register itself with the blockchain_state_channel_client handler so downlink packets can be returned to the source device correctly regardless of which module is currently active.
> setting sc downlink handler per active lora mod

- config/sys.config
- src/poc/miner_poc_grpc_client_statem.erl
These seed validators have been added to the rust light gateway's config but not to the miner's config. This change fixes that and allows for omitting the port number from the config since that has a reliable default value in 8080
> Adding missing additional seed validators to the config

- config/docker-val.config.src
- config/val.config.src
We need to set keys for the denylist properly on miners built with the mainnet validator profile so the proper denylist worker is started. This change does so for mainnet profiles (not testnet) and also disables the denylist for miners so they are no longer running the denylist.
> add denylist keys to mainnet vals to enable worker

- src/poc/miner_poc_grpc_client_statem.erl
After running the grpc poc infrastructure at scale for a few days we've found hotspots can get into the undesirable state of being connected to a validator that is maintaining stable grpc streams but is not keeping up with the chain or may not have the latest blocks available to validate the connected hotspots' challenges.
This change ensures that hotspots are able to bail off a poorly performing validator and search for a new one if the connected validator is not keeping up with the chain to roughly within 15 min (assuming 1 block/minute for a total block age allowance of 15 blocks behind).
> grpc poc statem block age timeout

- src/poc/miner_poc_grpc_client_statem.erl
when a client checks if they are the target with the challenger, it can receive a queued_poc response.  This means the challenger recognises the key as its own but there is no active POC as yet.
The client can then make the decision to retry the request again later.  When making that decision the challenger had to be behind the notifying validator.  With this change, the request will be retried when the notifying val and the challenger are at the same height.
> if challenger and notifier are same height, retry pocs with queued response

- src/poc/miner_poc_mgr.erl
This addresses additional instances of using the supplied ledger over refetching from the chain
> dont refetch ledger from chain when supplied in an event

- src/miner_val_heartbeat.erl
Relayed validators hurt the performance of the consensus group because they are not directly reachable by other CG members. In order to prevent them from being elected to consensus group, this change adds a check in the heartbeat logic for a public listening address for the validator in the peerbook  and skips the heartbeat if there is not one.
> Prevent relayed validators from heartbeating

- Makefile
- src/poc/miner_poc_grpc_client_statem.erl
- src/poc/miner_poc_mgr.erl
- retry check target requests if grpc req fails
- serialise check target requests, dont spawn off
- remove sync call during check target to blockchain_swarm:get_keys/0
- prevent connection close calls from crashing, if already dead
> various check target request improvements

- src/miner_restart_sup.erl
The PoC Statem isn't really doing anything on a validator build so suggested disabling completely. This is likely a tiny optimization but at the very least cleans up the conceptual model of the running system in the validator configuration.
> Disable hotspot's poc_statem on vals

- src/poc/miner_poc_mgr.erl
When generating ephemeral keys for a POC, a validator will generate key pairs.   The public key will be proposed in the its heartbeats and end up on the ledger proposed pocs CF, whilst the private key will be saved to a local rocks DB via miner_poc_mgr.
These two keys are intrinsically linked, if a public key is selected/promoted then in order for the POC to initiate the owning validator must still have the associated private key.  However the GC implementation for these key stores were running at a different cadence...the public keys would have a GC run every 101 blocks whilst the private keys would have a GC run every 50 blocks.
This allowed for the possibility of a local private key being removed prior to the public key. Should the public key then be selected the POC would fail.
This …
> harmonize local keys GC cadence with ledger key proposals GC interval

- config/testnet-sys.config
- do not use dns for seeds (that only provides mainnet seeds)
- add both testnet seeds to seed_nodes
- add aliases for the testnet seeds
- remove aliases for mainnet nodes
> update testnet config to reduce crosstalk with mainnet

- Makefile
- priv/gateway_rs/testnet.settings
Gateway-rs needs to support multiple default routers so it now takes a vector of keyed uris instead of a map keyed by the release channel. This updates the commit for the gateway-rs embedded in the erlang miner and the testnet configs for the embedded gateway to continue routing testnet packets to the testnet default router.
> update testnet gatewayrs configs for router list

- config/docker-testval.config.src
- config/test_val.config.src
Problem to solve: We may want to have multiple test nets running
Solution:  Parameterize some infrastructure pieces like seed nodes and default router
> Parameterize seeds and default router for testnet

- config/docker.config
Turn on the embedded rust light gateway and mux for dockerized miners
> enable the mux/embedded light gateway

- src/poc/miner_poc_grpc_client_statem.erl
Reduces the maximum block age a miner client will allow from a durable validator from 900 (roughly 15 min) to 600 (roughly 10 min) to ensure clients are ditching under-performing durable validators in favor of ones that are keeping better pace with the chain.
Also updates the timeout constant the client uses to trigger checks of a connected durable validator's block age to compute based on the maximum allowed block age. Keeps the formula previously in place but now computes it based on changes to the `MAX_BLOCK_AGE` to always be roughly half the allowed maximum block age in milliseconds. The check timeout is roughly half the allowed maximum block age plus a jitter of up to another half the allowed maximum block age.
> Reduce invalid block age threshold

- src/miner_query.erl
- src/poc/grpc_client_stream_custom.erl
- src/poc/miner_poc_grpc_client_statem.erl
- src/poc/miner_poc_mgr.erl
- test/miner_poc_grpc_SUITE.erl
1.  Adds a monitor to the stream process of the parent connection process. If that terminates then shutdown the stream process
2.  Specifies a timeout for unary grpc requests.  If no timeout is specified the grpc client lib would default to infinity
3.  Adds a query to find txns by onion key hash
4.  Logging tweaks
> stream related grpc client fixes

- src/miner_val_heartbeat.erl
Fixes a mistake in the lager warning message that kept the LISTEN_ADDRESSES from printing in the message
> fix heartbeat warning log message

- Makefile
The latest alpha26 tagged pre-release of the gateway-rs embedded in the miner includes some improvements to the gateway including supporting multiple default routers instead of a single one per release channel and supports retrieval of a `version_info()` API from durable validators to allow the gateway to refuse or reject a durable validator that is not running some minimum version of the miner/validator software once the gateway is no longer running the blockchain to allow feature-gating based on a chain var.
> pull in gateway-rs alpha26 pre-release

- config/docker.config
hotfix to bypass a packet routing issue in the embedded rust gateway while a pending fix is validated
> disable the mux to bypass an issue that requires testing

- src/poc/miner_poc_grpc_client_statem.erl
Fix a dialyzer warning cause by mistakenly stating that the sixth
element of the tuple that is cached for a target request is a function().
It is not; it's a binary() containing the challenger's signature.
> Fix dialyzer warning: 6th item in request tuple is binary, not function.

- test/miner_poc_grpc_SUITE.erl
This sets a chain var as part of the grpc test suite to enable `poc_witness_consideration_limit`.
With PR https://github.com/helium/blockchain-core/pull/1378 h3dex assumes this var is set. The var is already long enabled on mainnet but was never set in the test suite.
> set test chain var, required by h3dex targeting

- .buildkite/hooks/pre-command
Problem to solve: We are currently building debs using OTP22. Let's use 24 instead.
> Bump to OTP24 for (debian) builds

- src/poc/grpc_client_stream_custom.erl
Fixes incorrect use of the stream connection monitor var name from the state.  Connection monitor var is defined in state here:
https://github.com/helium/miner/blob/master/src/poc/grpc_client_stream_custom.erl#L73
Set here:
https://github.com/helium/miner/blob/master/src/poc/grpc_client_stream_custom.erl#L140
But the DOWN info handler was stupidly looking for `conn_mon` rather than `conn_monitor_ref`
Thanks to community member `nmc` for supplying logs highlighting the issue
> use correct monitor ref

- src/miner_ebus.erl
The pieces of the current implementation of the miner ebus api are being deprecated one by one, including the removal of asserting locations with the change to validator-initiated challenges and now with the disabling of miners following the chain breaking the height, blockage, and related status checks.
This change temporarily grants the ebus interface a stay of execution by having it call into the embedded gateway's local grpc api to retrieve the information and allow makers additional time to transition their firmware off the ebus interface to use the `gateway_config` application.
> shim gateway api into ebus interface

- src/poc/miner_poc_mgr.erl
Problem to solve: On new networks, the actual gateway count can be 0 which causes a crash in miner that prevents blocks from syncing.
Solution: Make the size of the new filter at least 1000, and if it's larger, use the actual gateway count for filter sizing.
> Make the smallest bloom filter 1000 elements

- src/handlers/miner_hbbft_handler.erl
- src/miner_hbbft_sidecar.erl
Adds a handler function for the `query_txn` / `update` transaction type that is now possible via the hbbft_sidecar's `handle_txn/2` api function.
> handle query_txn requests

- .buildkite/scripts/make_image.sh
The official erlang alpine image has updated its base to alpine 3.16 within the last week which is breaking the release now that our runner image is being built a minor version of alpine behind where the release is built. This causes runtime errors with `no symbol found`.
> update alpine runtime image

- config/docker-val.config.src
- config/sys.config
- config/val.config.src
This can't go in as-is since it will affect validators. I'm open to suggestions to get to the end goal of only disabling prewarm on miners.
> Disable cache prewarm on miners

- tag-release.sh
as long as we're tagging our releases with `tag-release.sh` and we don't plan to change the erlang versioning scheme or the tagging strategy for validator tags this should prevent us from publishing a validator release without first updating the version function in `src/miner.erl`
> prevent tagging validator release without updating version in miner.erl

- Dockerfile-ubuntu
The scanelf command is failing due to this a missing package. This change adds pax-utils to the apt packages installed in the builder image. The scanelf command is used to strip debugging symbols from the ERTS binaries thus reducing them and the final image in size by 40+MB .
> Add pax-utils to debian Dockerfile packages

- rebar.config
- scripts/extensions/denylist
- src/cli/miner_cli_denylist.erl
- src/cli/miner_cli_info.erl
- src/cli/miner_cli_registry.erl
- src/jsonrpc/miner_jsonrpc_denylist.erl
- src/miner_jsonrpc_handler.erl
Based on a request from the community, this change adds basic denylist functionality to the cli and jsonrpc endpoint. Supported methods are:
- `denylist status` which returns whether a denylist is loaded and if so which version
- `denylist check <address>` which returns whether or not the provided hotspot address is on the loaded list; will return true/false only if denylist is loaded and error if the address is not a valid b58 hotspot address
> Add denylist to cli and jsonrpc

- src/miner_lora.erl
rssis is supposed to be the useful signal strength
rssic is supposed to be the received signal strength
The blockchain expects the rssi to be the rssis. However when falling back to rssic when rssis is unavailable, the computation is wrong when SNR < 0
Indeed, in that case the useful signal strength is below the noise level, which is rssic. So the rssis = SNR + rssic when SNR < 0
This should help use the appropriate GWMPv2 value from the packet forwarders
> fix rssi computation from rssic if SNR < 0

- config/docker-val.config.src
- config/val.config.src
- src/miner_util.erl
since the miner stopped following the chain, not connecting to them blackholes a gossip link, making it hard for certain nodes to connect to active chain followers and stay synced.  this PR makes prefer non-miners as gossip peers, hopefully improving sync until we can remove the miners from the gossip network, at which point we can tune down the number of active connections.
> add ability to not gossip with miners

- src/poc/miner_poc_mgr.erl
This change addresses an edge case which can cause a validator to garbage collect a local poc private key before the public key is removed from the ledger leading to a failed PoC. The issue is caused by the fact that the local private key is stored with its height at the time of key/heartbeat creation while the public key is stored with the height at which the heartbeat is accepted on the blockchain. In typical cases, this differences between heartbeat creation and acceptance is only a few blocks. However, it can be longer under heavy network load or with an improperly functioning validator..
To address this case, this change extends the time that local poc key remains in the validator's key store by the validator liveliness heartbeat interval and grace period (currently 100 + 50 = 150 …
> Add heartbeat interval to local POC key lifespan

- src/jsonrpc/miner_jsonrpc_ledger.erl
Update the JSONRPC call for account balances to use ledger entry v2 when the token_version is set to 2 (or higher). This allows the JSONRPC call to continue to pull current balance since the MOBILE / subnetworks went were activated.
> Fix jsonrpc ledger balance for entry v2

- src/miner.erl
- src/miner_blockhistory.erl
- src/miner_restart_sup.erl
This PR tries to mitigate the penalties that occur when a validator has a block history that leads to a different target block time than the majority of the other validators. `miner_blockhistory` fetches the block time and height from 50k blocks ago every 5 minutes and caches it for the target block time calculation to use. If the validator has sufficient block history itself it will not use `miner_blockhistory` and when `miner_blockhistory` provides erroneous values they will also be disregarded.
> Use API for augmenting target block time calculation

- Dockerfile
rust gateway needs to be able to find a proprietary protobuf compiler package; the alpine `protobuf` package seems to be the equivalent of the debian-flavored version `protobuf-compiler`
> fix missing protobuf compiler package

- src/miner.erl
**Goal**: Reduce the variability of block times. 
We have observed a few issues with block times and validators. First, it seems that many validators struggle to keep up with extremely fast block times (i.e. 50s). By ramping up with the catchup times more gradually, we can hopefully avoid the need for 50s blocks and thus the performance hit to validators that come with them. 
Second, because many validator do not store at least 50K of block history, calculations of the target block time will vary between validators. Currently, this variability results in 9 or 10 second discrepancies between validator which may be resulting in missed BBAs for validators assuming the block time should be longer than the majority. By having more steps in the catchup ramp curve, we will hopefully see smaller …
> Make block time catchup proportional to drift
