- rebar.lock
- src/poc/miner_onion_server.erl
- test/miner_fake_radio_backplane.erl
- test/miner_onion_SUITE.erl
This is going to GA right now. Merge now?
> LongFi proto update

- src/poc/miner_poc_statem.erl
the `targeting` and `challenging`  states of the poc statem cannot be safely restored, so while we work on a better fix, just drop the restored state and go back to requesting.
> drop poc statem states we cannot safely restore

- rebar.lock
- src/miner.erl
- test/miner_ct_utils.erl
- test/miner_poc_SUITE.erl
- test/miner_txn_bundle_SUITE.erl
Related core PR: https://github.com/helium/blockchain-core/pull/294
> Add support for txn bundles

- test/miner_txn_bundle_SUITE.erl
This adds another bundle test for checking we don't allow bundles in a bundle txn.
> Add bundleception test

- rebar.lock
- src/poc/miner_onion_handler.erl
- src/poc/miner_poc_statem.erl
- test/miner_ct_utils.erl
- test/miner_fake_radio_backplane.erl
- test/miner_poc_SUITE.erl
- Add support for poc v4.
- Rework poc dist test cases.
> Integration for poc_v4

- src/poc/miner_onion_server.erl
- src/poc/miner_poc_statem.erl
See commit messages for details.
> Various improvements to PoC to increase the chances of getting receipts/witnesses

- src/miner_hbbft_sidecar.erl
this log line got dropped in the sidecar refactor
> log when we time out a validation

- priv/plot.gpt
- src/miner_plot.erl
> add the HNT produced as a ratio of the ideal rate

- rebar.config
- rebar.lock
- src/poc/miner_poc_statem.erl
- test/miner_poc_SUITE.erl
Add support and tests for poc v5
> Groundwork for POC V5

- rebar.config
> Standardize on upstream plugin

- src/cli/miner_cli_info.erl
Use lager base to derive logs path
> use lager log base for miner info summary 

- src/poc/miner_poc_statem.erl
Handle removed and no longer supported states read from the statem file during init of miner_poc_statem
All miners which were in this state will now default to requesting state
> handle removed states read from saved statem file during init

- rebar.config
- rebar.lock
Sets the source for blockchain-core to be https instead of git@ based
> Fix access for blockchain-core to not be private

- src/miner_consensus_mgr.erl
To prevent slow block gossip holding up a new round, try to fastforward
all the new group members to the same block as we have.
> Attempt to fast-forward new consensus members after election appears

- src/miner_consensus_mgr.erl
- src/miner_sup.erl
there are probably a few more things to work on, but this should narrow it down and take care of the most common ones.
> don't crash manager on busy dkg, don't die quite so easily

- src/miner_consensus_mgr.erl
the consensus manager shouldn't crash out if it doesn't know what to do with a restore, because this takes the whole system down.  It should just enter an idle state, so repair is possible.
> don't crash loop on ledger mismatch so we can attempt repair

- test/miner_ct_utils.erl
Add another helper function for checking whether a txn has appeared on the ct miners.
> Add helper wait_for_txn fun for testing

- src/miner_lora.erl
- test/miner_fake_radio_backplane.erl
Additionally fix an edge case when no gateways are connected and also
fix a bug in the fake radio backplane.
> Attempt to be more flexible about parsing Semtech JSON packets

- Makefile
- config/seed.config
- rebar.config
This branch brings in a number of optimizations specific to the seed nodes that haven't hit upstream yet.
> seed node target

- src/poc/miner_poc_statem.erl
we're seeing some issues where hotspots fall into sync mode and stop requesting for a long while.  allowing sync events to drive the statem when recent should allow them to challenge in a more timely fashion.
> allow recent sync to drive poc statem forward

- Makefile
- all-cmd.sh
- cmd.sh
- config/test.config
- rebar.config
- run.sh
- status.sh
fixup the configs so that dev is meant to be used as a syncing local miner and testdev is for `run.sh` & etc.
> tinker with configs a bit

- test/miner_poc_SUITE.erl
@andymck this should help with the failure we were seeing over on the "upload artifacts" branch.
> Wait for the consensus manager to be up before trying to talk to it

- test/miner_poc_SUITE.erl
> wait instead of using progress criteria, don't run old tests

- rebar.lock
- test/miner_payment_txn_SUITE.erl
- test/miner_payment_v2_txn_SUITE.erl
Related to: https://github.com/helium/blockchain-core/pull/421
> Add test for zero amount payment_v2 txns

- config/sys.config
- include/miner_util.hrl
- src/handlers/miner_hbbft_handler.erl
- src/miner_util.erl
add some basic instrumentation to the consensus group.
> instrument hbbft handler

- src/handlers/miner_hbbft_handler.erl
Fix some places where we would incorrectly drop signatures or not
transition to the gossip or done states.
> Plug some holes in the hbbft signature phase

- Makefile
- rebar.lock
- src/miner.erl
- src/miner_ebus.erl
This requires https://github.com/helium/blockchain-core/pull/221 to merge
> Remove blockchain txn helpers that moved to core

- src/miner_lora.erl
This was done for @lthiery to enable the development of a LoRaWAN protocol sniffer and he has confirmed it works.
> Optionally mirror all packet forwarder up/down packets to a seperate udp socket

- src/poc/miner_poc_statem.erl
If the submitting node is not more than 5 blocks behind the chain it
will never see its poc request hit the chain and thus end up in a loop
of never submitting receipts. This lengthens the poc request submission
timeout to the same as the poc interval and uses the transaction
callback to log if the receipt has been submitted.
> Relax poc receipt submit timeouts and track transactions via callbacks

- src/handlers/miner_hbbft_handler.erl
plugging a different hole in the hbbft state machine opened up one with seen tracking that caused a lot of votes to be discarded.  while debugging, I noticed bba and seen data is not zeroed out in a skip.
> plug holes in seen tracking

- .buildkite/pipeline.yml
- .buildkite/scripts/Dockerfile-amd64
- .buildkite/scripts/Dockerfile-arm32
- .buildkite/scripts/Dockerfile-arm64
- .buildkite/scripts/make_amd64_docker.sh
- .buildkite/scripts/make_arm32_docker.sh
- .buildkite/scripts/make_arm64_docker.sh
The `Dockerfile` builds and runs miner inside a container using QEMU.
> Build miner inside Docker container for aarch64

- config/sys.config
- rebar.lock
> update assumed valid and blockchain dep

- config/sys.config
- config/test.config
- rebar.lock
bump assumed valid, upgrade blockchain with snap fixes, correct sys.config sync settings
> snaps try 3

- src/handlers/miner_hbbft_handler.erl
taking a snapshot can error, don't try to contribute if you cannot safely construct a snapshot.
> ignore if we can't take a snapshot

- config/sys.config
First snapshot meant for deploying to production.
> Bump blessed snapshot to 352081

- .buildkite/pipeline.yml
Tested this with some tags (that are now deleted) and the Docker builds were appropriately triggered.
> Fix Pipeline Names and Add Conditional Build on _GA Suffix

- src/miner_lora.erl
sorry, brain failure due to living in performance land for a week.
> GPS fix went in the wrong direction

- config/dev.config
- config/sys.config
- rebar.lock
support for https://github.com/helium/blockchain-core/pull/506
> adjust cache limits

- src/poc/miner_poc_statem.erl
this is not an interesting error:
```
2020-06-25 11:47:07.450 [warning] <0.1515.0>@miner_poc_statem:allow_request:653 error determining if request allowed: error:{badmatch,{error,not_found}} [{miner_poc_statem,allow_request,2,[{file,"/Users/evan/src/miner4/src/poc/miner_poc_statem.erl"},{line,635}]},{miner_poc_statem,requesting,3,[{file,"/Users/evan/src/miner4/src/poc/miner_poc_statem.erl"},{line,169}]},{gen_statem,loop_state_callback,11,[{file,"gen_statem.erl"},{line,1118}]},{proc_lib,wake_up,3,[{file,"proc_lib.erl"},{line,259}]}]
```
> silence useless error output on full nodes

- audit/var-14.md
- audit/var-15.md
- audit/var-31.md
> add var 31 and backfill 14 and 15

- .buildkite/pipeline.yml
Can't really test this until the next _GA tag.
> Remove OCI images from CD pipeline

- src/poc/miner_poc_statem.erl
this is the simplest remedy for the crash when we have old data in the statem retained state.  a more complete fix would take things that are protobufs an encode/decode them on serialize/deserialize.  that said, each individual PoC is fairly low value, so it might make more sense just to give up.
> ignore crashes when we're submitting a txn and give up on that poc

- src/miner_lora.erl
It's not possible to see downlinks with the current log configuration. This mirrors the `info` level of PUSH_DATA (uplinks) with PULL_RESP frames output at the `info` level.
> expose PULL_RESP frames to info logs

- src/miner_consensus_mgr.erl
- src/miner_critical_sup.erl
- src/miner_restart_sup.erl
- src/miner_sup.erl
make it so when the blockchain or the consensus manager is sad, the whole node just bails immediately.
> rework supervisors

- config/sys.config
Height 468721
Hash <<87,74,66,183,209,50,51,113,153,250,112,176,6,49,75,59,208,212,111,2,66,
208,90,2,140,87,112,185,27,7,246,184>>
> Bump blessed snapshot to 468721

- config/sys.config
> Forgot a closing curly brace

- src/miner_keys.erl
> Do not double match OnboardingKey

- rebar.lock
- src/poc/miner_poc_statem.erl
> Add support for poc_per_hop_max_witnesses

- config/test.config
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
- test/miner_payment_txn_SUITE.erl
- test/miner_payment_v2_txn_SUITE.erl
- test/miner_poc_SUITE.erl
- test/miner_reward_SUITE.erl
- test/miner_router_SUITE.erl
- test/miner_txn_mgr_SUITE.erl
> improve init_per_testcase and election test

- config/test.config
- rebar.lock
- test/block_listener.erl
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
- test/miner_fake_radio_backplane.erl
- test/miner_poc_SUITE.erl
- test/miner_state_channel_SUITE.erl
de-copy-paste all the tests, speed them up etc.  needs a blockchain core branch for full effect.  the `client_reports_overspend_test` is still broken and I need some help with it.
> substantial state channel test rework

- rebar.config
- rebar.lock
- test/miner_ct_utils.erl
- test/miner_state_channel_SUITE.erl
Companion test for https://github.com/helium/blockchain-core/pull/627
> Test that state channel closes within grace blocks of an epoch end are rewarded

- config/sys.config
```
Height 540721
Hash <<220,233,129,26,150,56,39,164,156,107,235,115,246,126,77,189,168,42,102,
25,58,22,233,131,20,66,218,205,64,153,70,59>>
Have true
```
> Update blessed snapshot to 540721

- src/miner_lora_throttle.erl
`miner_lora_throttle` is not handling the case of when the current region is `undefined` (AKA not yet know), leading to a match failure. This PR crates a new throttle pattern defined as `'unsupported'` and all calls with that handle are no-ops. When the region is callback finally fires in `miner_lora`, the `'unsupported'` handle is replaced with one that does proper throttling.
> Handle unsupported region

- src/miner.erl
Miner side of https://github.com/helium/blockchain-core/pull/510
> support branch for meaningful invalid txn msgs

- test/miner_state_channel_SUITE.erl
- test/miner_test_sc_packet_handler.erl
This fixes the SC tests after an API change and updates core with another test-related fix.
> test fixes

- run.sh
- src/cli/miner_cli_genesis.erl
this should make it work right from a clean compile.
> fix run.sh to run out of the box

- config/sys.config
```
Height 583201
Hash <<118,167,69,0,64,215,38,50,120,201,248,84,243,97,247,71,177,40,241,14,3,
246,89,135,84,2,116,250,181,136,35,190>>
Have true
```
> Bump snap to 583201

- config/sys.config
Height 591841
Hash <<201,205,253,51,241,181,82,117,108,54,94,109,157,0,0,42,169,65,13,14,151,
136,232,135,60,132,81,56,45,128,129,241>>
Have true
> Bump snap to 591841

- src/poc/miner_onion_server.erl
Set the TX power correctly for US915 and EU868 PoC packets
> Dynamically select PoC TX power by region

- src/miner.erl
- src/miner_keys.erl
add retries to miner keys ecc interaction, cache sigfun and key in miner state
> some crash cleanups

- src/miner_consensus_mgr.erl
Miner can crash without bringing the node down (the case I saw was the sidecar failing to rocks issues and taking the miner down with it).  If we're in a group, this can leave us in the state where we think that we're out, and not setting timers correctly.   This PR has the consensus manager watch for this and install group back onto the restarted miner server.
> monitor miner

- .buildkite/pipeline.yml
- .buildkite/scripts/Dockerfile-val-arm64
Pretty self-explanatory, just added build pipeline change + Dockerfile for an arm64 validator image.
> Adding arm64 support for validator branch.

- config/sys.config
IPs have changed, point the sys config to the new infrastructure.
> update seed nodes

- src/miner_keys.erl
get_public_key had the nasty sideeffect of generating keys when they were not found in a slot.
In the new Maker world the public key is intended to be the onbarding key which means slot 15 was empty, but the code was still generating a key there which was then wrongly used as the onboarding key. This fix will correct that, and safe because slot 0 is already populated by a key by gateway_mfr
Old hotspots that were not provisioned with a slot 0 key will have old miner_keys code that _will_ generate a key in slot 0 before they get an OTA
> Remove key generation from get_public_key

- .buildkite/pipeline.yml
- .buildkite/scripts/make_deb.sh
- .buildkite/scripts/packagecloud_upload.sh
- deb/miner.service
Problem to solve: We want to publish a debian package for the validator builds
Solution: Build a debian and push it to a public repo on packagecloud
> Build and upload validator debian package

- src/handlers/miner_dkg_handler.erl
enough_signatures was doing a lot of redundant work we didn't really need and we had a bunch of redundant termination clauses. This reworks the signature checking so we check each valid signature only once and reject duplicate/extra signatures from members.
> Rework DKG signature phase to be simpler and more efficent

- src/handlers/miner_hbbft_handler.erl
- src/miner.erl
- src/miner_util.erl
Enhancing understandability and Dialyzability. Not done yet.
> Refactor create_block

- config/sys.config
I am re-adding staging in `node_aliases` as we have seen with @lthiery  a fair amount of issue resolving IP.
> Add staging in node_aliases

- README.md
Updating Readme for current supported version of Erland OTP.
> Update Readme for Erlang OTP 23.

- config/sys.config
```
Height 819361
Hash <<37,200,34,196,159,21,177,153,141,137,61,43,16,186,134,16,55,179,91,55,
157,250,211,39,191,219,188,58,36,12,164,240>>
Have true
```
> Bump snap to 819361

- .buildkite/scripts/Dockerfile-amd64
- .buildkite/scripts/Dockerfile-arm64
This is the only change required to fix the docker cli brokenness I believe
> Use local rebar when building docker rel tarball

- rebar.lock
- src/miner_util.erl
- src/poc/miner_onion_server.erl
- src/poc/miner_poc_statem.erl
- test/miner_poc_SUITE.erl
Linked blockchain core PR: https://github.com/helium/blockchain-core/pull/754
Add capability check to the POC flows.  If a GW does not have the required capability for example to send POC requests, then it will be prevented from doing so.
> Check gateway capabilities in POC flows

- config/sys.config
Height 841681
Hash <<62,60,211,231,202,64,190,6,57,42,6,194,142,137,213,114,227,198,155,51,
247,198,27,34,28,33,168,136,129,218,141,42>>
Have true
> Update snapshot to 841681

- config/sys.config
Height 851041
Hash <<139,240,52,42,109,113,216,234,234,0,105,101,50,223,58,4,114,6,167,55,74,
220,27,58,179,23,130,28,23,28,214,41>>
Have true
> Update snap to 851041

- .buildkite/pipeline.yml
- .buildkite/scripts/make_image.sh
Problem to solve: We want to build docker containers on all tagged releases of miner, but only tag a release as `latest` if it has `_GA$`
> Build docker images on all tags

- .buildkite/scripts/make_image.sh
Problem: `[` only works with numbers
> Use the [[ operator not [

- src/cli/miner_cli_dkg.erl
- src/miner_consensus_mgr.erl
the election info API has changed, but we didn't adjust calls to it.
> fix election info calls

- src/miner.erl
- src/miner_.erl
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
> Test time-based skip voting

- config/sys.config
- rebar.lock
```
Height 879121
Hash <<108,52,90,47,22,227,230,0,129,189,174,215,157,123,94,182,119,28,89,162,
97,140,151,229,28,26,141,123,212,72,251,89>> (<<"6c345a2f16e3e60081bdaed79d7b5eb6771c59a2618c97e51c1a8d7bd448fb59">>)
Have true
```
> Update core, new snap-879121

- src/miner_consensus_mgr.erl
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
- test/miner_dkg_SUITE.erl
- test/miner_packet_routing_SUITE.erl
- test/miner_payment_txn_SUITE.erl
- test/miner_payment_v2_txn_SUITE.erl
- test/miner_poc_SUITE.erl
- test/miner_reward_SUITE.erl
- test/miner_router_SUITE.erl
- test/miner_state_channel_SUITE.erl
- test/miner_transfer_hotspot_txn_SUITE.erl
- test/miner_txn_bundle_SUITE.erl
- test/miner_txn_mgr_SUITE.erl
- test/miner_witness_SUITE.erl
Rework miner_ct_utils:initial_dkg to account for partial completion
Refactor tests for new miner_ct_utils:initial_dkg
This is to land #802 retargeted to the master branch
> refactor txn mgr dependency test

- src/poc/miner_onion_server.erl
Somehow these specs were busted on miner:master, fixed here
> Fix onion_server specs

- config/sys.config
```
Height 882721
Hash <<116,176,240,96,9,33,57,140,155,11,53,246,224,32,130,230,232,130,241,236,
115,56,194,42,246,102,191,63,31,68,70,112>> (<<"74b0f0600921398c9b0b35f6e02082e6e882f1ec7338c22af666bf3f1f444670">>)
Have true
```
> Bump to snap-882721

- src/miner_consensus_mgr.erl
this is one of the last blockers before we merge the `pevm/validators` branch to master.  ideally we would not waste resources on these before we need to.
> penalty txns are invalid before election v5, so don't start them

- src/handlers/miner_hbbft_handler.erl
- test/miner_blockchain_SUITE.erl
- test/miner_ct_utils.erl
> Implement and test var-autoskip

- src/jsonrpc/miner_jsonrpc_ledger.erl
- src/jsonrpc/miner_jsonrpc_peer.erl
- src/jsonrpc/miner_jsonrpc_sc.erl
- src/jsonrpc/miner_jsonrpc_txns.erl
- src/miner_jsonrpc_handler.erl
Problem to solve: Dialyzer found a number of issues with JSONRPC calls and types. Fix them.
> Make dialyzer happy with JSONRPC

- config/sys.config
```
Height 894961
Hash <<22,241,2,72,52,202,53,60,32,250,165,93,161,18,184,189,113,205,54,228,
194,150,191,70,81,68,163,217,228,12,240,124>> (<<"16f1024834ca353c20faa55da112b8bd71cd36e4c296bf465144a3d9e40cf07c">>)
Have true
```
> Update to snap-894961

- config/sys.config
```
Height 896401
Hash <<171,79,9,161,214,170,39,126,12,142,57,133,45,136,49,131,197,254,11,255,
0,255,152,1,5,116,202,193,219,174,226,230>> (<<"ab4f09a1d6aa277e0c8e39852d883183c5fe0bff00ff98010574cac1dbaee2e6">>)
Have true
```
> Update blessed snap to 896401

- config/sys.config
- config/test.config
- config/test_val.config.src
autoskip shipped with a too-short timeout, make it much longer.
> reconfigure autoskip and ports

- .buildkite/env/secrets.ejson
- .buildkite/hooks/pre-command
- .buildkite/pipeline.yml
Moves the asdf setup steps to a pre-command hook to ensure it's visible in all steps
> move environment setup to a pre-command hook

- config/sys.config
- rebar.lock
- New blessed snap-899281
```
Height 899281
Hash <<161,144,190,40,123,158,116,17,24,0,135,49,87,60,87,110,54,0,244,16,236,
110,207,137,101,173,9,36,75,149,211,43>> (<<"a190be287b9e741118008731573c576e3600f410ec6ecf8965ad09244b95d32b">>)
Have true
```
> Update for core#746 and core#375

- config/sys.config
```
Height 900001
Hash <<228,126,211,62,153,16,6,154,130,180,132,255,106,149,127,246,203,218,21,
13,3,33,141,102,240,100,196,187,162,75,195,151>> (<<"e47ed33e9910069a82b484ff6a957ff6cbda150d03218d66f064c4bba24bc397">>)
Have true
```
> Update blessed snap-900001

- src/cli/miner_cli_hbbft.erl
not sure we'd tried this before it merged.
> fix hbbft perf for pre-validator code

- config/sys.config
```
Height 900721
Hash <<38,86,48,8,188,202,169,31,177,199,132,220,205,202,149,78,83,208,244,148,
103,249,230,4,204,152,32,124,48,239,212,25>> (<<"26563008bccaa91fb1c784dccdca954e53d0f49467f9e604cc98207c30efd419">>)
Have true
```
> Update blessed snap-900721

- config/sys.config
```
Height 910531
Hash <<95,253,152,33,253,132,175,201,16,213,118,213,1,87,113,203,209,242,143,
230,104,213,232,83,61,173,201,176,206,176,178,42>> (<<"5ffd9821fd84afc910d576d5015771cbd1f28fe668d5e8533dadc9b0ceb0b22a">>)
```
> Update to snap-910531

- src/miner_app.erl
since we have moved the consensus group to the validator, there's no point in the gateways validating increasingly expensive transactions as they can no longer participate in consensus.
> put all gateways into non-validating mode

- config/docker-val.config.src
- config/sys.config
- config/val.config.src
- src/miner_app.erl
new chain snap for release, all gateways into follow mode.
> Add snap, global follow mode

- config/sys.config
```
Height 941761
Hash <<18,194,33,227,105,130,96,10,127,91,238,90,123,188,172,157,123,140,162,
40,15,117,155,101,140,198,79,7,200,192,16,79>> (<<"12c221e36982600a7f5bee5a7bbcac9d7b8ca2280f759b658cc64f07c8c0104f">>)
Have true
```
> Update blessed snap-941761

- src/handlers/miner_hbbft_handler.erl
- src/miner_util.erl
> add rescue block utility function

- config/sys.config
```
Height 975601
Hash <<87,86,149,234,13,212,196,250,56,57,160,76,150,198,152,134,4,189,17,109,
213,98,182,6,194,119,59,127,120,219,229,108>> (<<"575695ea0dd4c4fa3839a04c96c6988604bd116dd562b606c2773b7f78dbe56c">>)
Have true
```
> Update snap to 975601

- .buildkite/pipeline.yml
- .buildkite/scripts/make_deb.sh
the raw tagging isn't working, depending on the tag, so specify until we can get relx fixed
> use correct arguments for building miner for the deb

- test/miner_state_channel_SUITE.erl
This just fixes some of the obvious brokenness, doesn't resolve everything.
> Fix some of the state channel tests to call newer functions

- src/miner_val_heartbeat.erl
everything went to debug, but it'd be nice to have at least some logging here.
> log more when doing heartbeat txns

- src/poc/miner_poc_statem.erl
I think that using a bloom filter as per #714 is both overcomplicated and biases witness selection in an odd way.  I'd like to try this first; This PR simply accumulates all of the witnesses and takes a random slice of them, which should be fairer.
> use a random selection of witnesses instead of the first LIMIT

- src/handlers/miner_hbbft_handler.erl
- src/miner_util.erl
- src/poc/miner_poc_statem.erl
this follows the API changes, but the tests are in a pretty parlous state right now, so a low-confidence change.
> update for mode and snapshot changes from core

- .buildkite/scripts/make_image.sh
Problem to solve: Using `basename` on build types other than `miner` is incorrect.
> Don't use the basename unless it's miner

- config/test_val.config.src
Problem to solve: We need to add the IP addresses for testnet seed nodes.
> Add ips for testnet seed nodes

- .buildkite/scripts/make_image.sh
Problem to solve: The registry host was inadvertently duplicated. Copypasta errors are killers.
> Don't duplicate hostname twice

- src/miner_lora.erl
> use rssis only if present in json

- src/poc/miner_onion.erl
- src/poc/miner_onion_server.erl
- src/poc/miner_poc.erl
- src/poc/miner_poc_statem.erl
Miner side changes parallel to https://github.com/helium/blockchain-core/pull/1019
> Switch to use SwarmTID when dialing framed streams

- src/miner_lora_throttle.erl
Fixes https://github.com/helium/miner/issues/1094
> Fix missing AS923-4 region in miner_lora_throttle

- config/sys.config
- rebar.lock
```
Height 1059841
Hash <<247,212,41,146,24,101,213,23,115,218,6,119,182,57,96,148,156,237,134,
172,105,169,155,95,31,126,253,16,58,161,113,235>> (<<"f7d429921865d51773da0677b63960949ced86ac69a99b5f1f7efd103aa171eb">>)
Have false
```
> Update core and bump to snap-1059841

- src/miner_lora.erl
Problem
----
Reported by the router team that `AdjustedTime` can become negative resulting in packets not being delivered.
Solution
----
Revert to the previous way of creating the packet but to still address https://github.com/helium/miner/issues/1132 , there's a case to set `When = 0` when `When = immediate`
> Do not use AdjustedTmst_us for tmst

- rebar.lock
Update for https://github.com/helium/blockchain-core/pull/1063
> Bump core for gossip fix

- src/jsonrpc/miner_jsonrpc_info.erl
- src/jsonrpc/miner_jsonrpc_ledger.erl
Add JSONRPC methods for 'version' which returns the semver build version (e.g., 1.4.5 or 2021.10.07.0) and 'ledger_gateways' with a "address" parameter to return ledger information for a single gateway.
Also, includes changes to the gateways output formatting to change location to h3 hex instead of integer and correct the animal name.
> Add jsonrpc methods for ledger_gateway with address and version

- src/miner_lora.erl
Guard lookup for regulatory regions further behind `poc_version > 10` check.
> More poc-v11 guard checks

- rebar.config
- rebar.lock
Bump longfi to a version with better support for cross-compilation and no semantic changes.
Closes #1164
CC @BenoitDuffez
> Bump LongFI

- src/poc/miner_poc_statem.erl
If witnesses are reported with `0.0` frequency, don't send.
> Drop 0.0 freq witnesses

- test/miner_blockchain_SUITE.erl
- test/miner_dkg_SUITE.erl
- test/miner_payment_txn_SUITE.erl
- test/miner_payment_v2_txn_SUITE.erl
- test/miner_reward_SUITE.erl
- test/miner_router_SUITE.erl
- test/miner_transfer_hotspot_txn_SUITE.erl
- test/miner_txn_bundle_SUITE.erl
- test/miner_txn_mgr_SUITE.erl
This PR for just notes. Each relocation will have its own PR.
> Springboard notes for tests relocations and improvements

- audit/var-101.md
> Add audit 101

- .buildkite/pipeline.yml
This hopefuly helps fool rebar into picking the rigth one
> strip all tags except the current active

- src/miner_consensus_mgr.erl
with these huge blocks, we've seen some cold start issues, this should help with them.
> in case of a long startup, keep checking for the chain

- config/sys.config
- rebar.lock
```
Height 1118110
NumBlocks 72
StartBlockHt 1118089
EndBlockHt 1118160
Hash <<127,204,161,67,65,97,118,98,168,208,165,210,45,123,135,53,213,17,178,88,
166,124,83,82,145,99,78,135,242,204,121,102>> (<<"7fcca14341617662a8d0a5d22d7b8735d511b258a67c535291634e87f2cc7966">>)
```
> Bump core and update blessed snap

- test/miner_blockchain_SUITE.erl
@evanmcc sorry, I missed those in #986
> Remove stale helper functions from tests

- audit/var-108.md
- audit/var-109.md
Audit for var nonce: 108 and 109
> Audit 108, 109

- .buildkite/pipeline.yml
- .buildkite/scripts/make_image.sh
Quality of life change to help people outside of Helium create builds more easily.
> Add registry org env

- config/sys.config
- rebar.lock
```
Height 1146910
NumBlocks 71
StartBlockHt 1146890
EndBlockHt 1146960
Hash <<211,88,96,84,117,231,208,6,200,22,198,103,145,251,139,142,187,177,122,
122,162,213,216,223,42,51,2,123,136,23,134,180>> (<<"d358605475e7d006c816c66791fb8b8ebbb17a7aa2d5d8df2a33027b881786b4">>)
```
> Bump core, update blessed snap-1146961

- src/poc/miner_onion_server.erl
re: https://github.com/helium/miner/issues/1238
> added logging for successful witness delivery

- src/miner_restart_sup.erl
Problem to solve: Tests abort because when a test scenario starts up a fleet of miners they all try to bind to port 4467 for JSONRPC.
Solution: During tests, choose a random high port for JSONRPC to bind to.
> Choose a random high port for JSONRPC during tests

- rebar.lock
- src/poc/miner_onion_server.erl
- test/miner_onion_SUITE.erl
code adjustment for recent changes to poc storage.
> move onion_server to new pocs api and fix onion test

- audit/var-117.md
- audit/var-118.md
> Add audits for var-117 and var-118

- config/docker-val.config.src
- config/sys.config
- config/val.config.src
- rebar.lock
- src/miner.erl
> start rollup for 1.7 release

- src/jsonrpc/miner_jsonrpc_txn.erl
Fixes the dialyzer error on `txns add_gateway`
> Fixing add_gateway call to use add_gateway/4

- src/poc/miner_poc_denylist.erl
> Make denylist regression check & check binary serial number

- rebar.config
- rebar.lock
- src/poc/miner_poc_statem.erl
- test/miner_poc_SUITE.erl
Miner side PR of core h3dex:
https://github.com/helium/blockchain-core/pull/1214
> support h3dex based targeting

- rebar.lock
Updated sibyl includes logging downgrades
> bump sibyl

- priv/gateway_rs/testnet.settings
Add a testnet router to the testnet gateway-rs config append file
> include testnet router in gateway-rs config

- .buildkite/scripts/make_deb.sh
- .buildkite/scripts/packagecloud_upload.sh
- .gitignore
- deb/after_install.sh
- deb/after_remove.sh
- deb/after_upgrade.sh
- deb/before_install.sh
- deb/before_upgrade.sh
- deb/miner.service
Incorporate #1402 and add the hotfix directory creation
> Incorporate debian package enhancements

- src/miner_lora_light.erl
- test/miner_gateway_mux_integration_SUITE.erl
These must have gotten munged in a rebase conflict resolution, as this module and the tests were all working when I originally pushed them up for initial review
> Fix rebase typos

- src/poc/miner_poc_mgr.erl
When a POC times out, the receipt txn is submitted by the challenger.  However if there are zero responses ( witnesses or receipt from the beaconer ) then dont submit the receipts txn.  This keeps validator challenges consistent with the previous hotspot challenger behaviour, see https://github.com/helium/miner/blob/master/src/poc/miner_poc_statem.erl#L284
> if no responses to a challenge, dont submit the receipt txn

- audit/var-129.md
Enable support for light gateways.
> Add audit for var-129

- src/poc/miner_poc_grpc_client_statem.erl
Using a configurable delay with a default of 30s, this should give the validator time to catch up.
> Add a delay between send_report retries

- src/poc/miner_poc_grpc_client_statem.erl
This lager statement is missing the necessary format string token
> fix bad format string in poc statem

- audit/var-136.md
Audit poc rate reduction from 700 to 200
Accepted https://explorer.helium.com/txns/0Mhfky9sDvq9vrcahJjQhvKHG4H4M6pqV79Sck_xICs
> audit poc_rate var 136

- src/miner_hbbft_sidecar.erl
Institute rudimentary validation counts on txns per hbbft round in the validation sidecar. Each round, internally collect a count of txns by type, grouped by validation result and emit the counts at the reset of each round in a log message
> Attempt count/log validation results by type per round in sidecar

- src/poc/miner_poc_grpc_client_statem.erl
This removes the restriction that limited the grpc client check target retries to 80% off the poc lifespan.  Now check target retries will continue until the POC lifespan has expired.
> allow check target reqs to be retried full duration of a POC

- .buildkite/pipeline.yml
- .buildkite/scripts/make_image.sh
create and push images to a devnet repository based on git tags similar to testnet
> accommodate devnet builds in the build pipeline

- .buildkite/pipeline.yml
- .buildkite/scripts/make_deb.sh
- .buildkite/scripts/packagecloud_upload.sh
Problem to solve: We need to build and publish debian packages of testnet validator releases.
> Build and publish testnet validator debs

- .buildkite/pipeline.yml
- .buildkite/scripts/make_deb.sh
> Make sure we use the right release target

- priv/gateway_rs/devnet.settings
Add a gateway-rs override file for devnet docker containers
> Add gateway-rs override for devnet

- src/poc/miner_poc_denylist.erl
prevent the denylist from crashing the miner during the boot process (when an exception is raised during the denylist init) or else crashing the denylist process continually if the signature verification over the denylist should fail at any future point following initial boot.
> handle exceptions in the lists:any/2

- config/sys.config
- config/testnet-sys.config
- rebar.lock
Miner side of https://github.com/helium/sibyl/pull/67
> add fun for denylist check

- audit/var-144.md
Had a small typo in the audit.
> Fix audit for var-144

- .buildkite/scripts/make_image.sh
- Dockerfile-ubuntu
- src/miner_hbbft_sidecar.erl
Less disruptive version of  #1488
> Use a different Dockerfile for validator builds

- rebar.lock
bump http2 client, pull in fix  https://github.com/helium/http2_client/commit/3d4d4e288b9deae0d7598397d2e7fe2396b9905d
> bump http2 client, pull in settings flag fix

- config/sys.config
- src/miner.app.src
https://github.com/helium/denylist/pull/8255
> Adding new denylist key as proposed

- src/miner.erl
> Revert "Make block time catchup proportional to drift"

- rebar.lock
- src/miner.erl
Depends on helium/blockchain-core#1519
> If the `isolate_var_txns` var is set, put var txns in their own block
